Repository rstudio/rstudio, pull requests merged in 2019-12, with the labels that each got.

#5810 accessibility fixes to Import Data dialogs
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentTab.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportFileChooser.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportModes.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUi.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsvLocale.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiJdbc.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiJdbc.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiJson.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiJson.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiMongo.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiMongo.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiOdbc.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiOdbc.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiSav.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXml.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXml.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
Labels: accessibility

#5815 remove multi-select capability from choose encoding dialog listbox
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/ChooseEncodingDialog.java
Labels: accessibility

#5816 fix accessibility of Find in Files when custom pattern option is selected
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
Labels: accessibility

#5817 associate label with field in About dialog (pro license status)
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/widget/FormTextArea.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.ui.xml
Labels: accessibility

#5821 Allow user selection of text in VCS diffs
  NEWS.md
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/diff/LineTableViewCellTableStyle.css
Labels: vcs

#5843 install binary keyring package
  src/cpp/session/resources/dependencies/r-packages.json
Labels: r packages

#5829 fix tab-trap in gitignore edit field
  src/gwt/src/org/rstudio/studio/client/common/vcs/ignore/IgnoreDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
Labels: accessibility

#5847 fix links in Ask Secret and RS Connect dialogs to work with keyboard
  src/gwt/src/org/rstudio/studio/client/common/rstudioapi/ui/AskSecretDialog.java
  src/gwt/src/org/rstudio/studio/client/common/rstudioapi/ui/AskSecretDialog.ui.xml
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.ui.xml
Labels: accessibility

#5859 use html input type=number instead of emulating in JavaScript
  src/cpp/desktop/DesktopInputDialog.cpp
  src/gwt/src/org/rstudio/core/client/widget/NumericTextBox.java
Labels: accessibility

#5861 fix layout of "save workspace" preference control
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Labels: user preferences

#5857 enable target directory selection in Upload Files dialog
  NEWS.md
  src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
  src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
  src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileUploadDialog.java
Labels: files pane

#5864 hide "Run Selection as Job" commands on Code menu when not supported
  src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java
Labels: jobs

#5868 variety of terminal-related enhancements
  NEWS.md
  src/cpp/session/SessionModuleContext.cpp
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcessInfo.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileCommandToolbar.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTab.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/CreateNewTerminalEvent.java
Labels: terminal

#5870 avoid invalid with/height redirects & increase maximum plot size
  src/cpp/session/modules/SessionPlots.cpp
Labels: plots

#5879 associate labels with controls in spelling dialog
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/spelling/SpellingDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/spelling/SpellingDialog.ui.xml
Labels: accessibility, spellcheck

#5876 fix accessibility of SVN Resolve dialog
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNResolveDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNResolveDialog.ui.xml
Labels: accessibility, vcs

#5874 add commands for zooming left/right UI columns
  NEWS.md
  src/gwt/src/org/rstudio/core/client/MathUtil.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermTheme.java
Labels: accessibility

#5884 add more control over terminal behavior after shell exits (user pref)
  src/cpp/session/SessionConsoleProcess.cpp
  src/cpp/session/SessionConsoleProcessInfo.cpp
  src/cpp/session/include/session/SessionConsoleProcessInfo.hpp
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcessInfo.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
Labels: terminal

#5885 fix text color of username when toolbar hidden
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/header/MenubarPanel.css
Labels: accessibility, themes

#5887 use focus-visible polyfill on sign-in page
  src/gwt/www/css/focus-visible.css
  src/gwt/www/templates/encrypted-sign-in.htm
Labels: accessibility

#5893 Accessibility command to put focus on main toolbar
  src/gwt/src/org/rstudio/core/client/a11y/A11y.java
  src/gwt/src/org/rstudio/core/client/widget/AriaLiveStatusWidget.java
  src/gwt/src/org/rstudio/core/client/widget/FilterWidget.java
  src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
  src/gwt/src/org/rstudio/core/client/widget/SearchWidget.java
  src/gwt/src/org/rstudio/core/client/widget/SearchWidget.ui.xml
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/application/ApplicationView.java
  src/gwt/src/org/rstudio/studio/client/application/events/ApplicationEventHandlers.java
  src/gwt/src/org/rstudio/studio/client/application/events/AriaLiveClearStatusEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/AriaLiveStatusEvent.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
  src/gwt/src/org/rstudio/studio/client/application/ui/GlobalToolbar.java
  src/gwt/src/org/rstudio/studio/client/application/ui/LauncherSessionStatus.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/application/ui/serializationprogress/ApplicationSerializationProgressLabel.java
  src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
Labels: accessibility

#5900 Improve accessibility in replace results
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutput.css
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindResult.java
Labels: accessibility, find in files

#5898 bump RSA key size to 2048
  NEWS.md
  src/cpp/core/system/Crypto.cpp
Labels: security

#5903 Use html numeric textfield for integer input in preferences panes
  src/gwt/src/org/rstudio/core/client/widget/NumericTextBox.java
  src/gwt/src/org/rstudio/core/client/widget/NumericValueWidget.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectEditingPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesPane.java
Labels: accessibility

#5909 Add Shiny background jobs
  NEWS.md
  src/cpp/session/CMakeLists.txt
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/modules/SessionShinyViewer.R
  src/cpp/session/modules/SessionShinyViewer.cpp
  src/cpp/session/modules/jobs/AsyncRJobManager.cpp
  src/cpp/session/modules/jobs/AsyncRJobManager.hpp
  src/cpp/session/modules/jobs/ScriptJob.cpp
  src/cpp/session/modules/jobs/ScriptJob.hpp
  src/cpp/session/modules/shiny/ShinyAsyncJob.cpp
  src/cpp/session/modules/shiny/ShinyAsyncJob.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/studio/client/RStudio.java
  src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java
  src/gwt/src/org/rstudio/studio/client/common/shiny/model/ShinyServerOperations.java
  src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
  src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplication.java
  src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplicationPresenter.java
  src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplicationSatellite.java
  src/gwt/src/org/rstudio/studio/client/shiny/events/LaunchShinyApplicationEvent.java
  src/gwt/src/org/rstudio/studio/client/shiny/model/ShinyApplicationParams.java
  src/gwt/src/org/rstudio/studio/client/shiny/ui/ShinyViewerTypePopupMenu.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionShinyHost.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Labels: shiny

#5916 add Sign Out command to File menu
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/signOut.png
  src/gwt/src/org/rstudio/studio/client/workbench/commands/signOut_2x.png
Labels: accessibility

#5918 remove focus rectangles around menus
  src/gwt/www/css/focus-visible.css
Labels: accessibility

#5915 (cleanup) use GWT roles for alerts instead of custom code
  src/gwt/src/org/rstudio/core/client/a11y/A11y.java
  src/gwt/src/org/rstudio/core/client/widget/InfoBar.java
  src/gwt/src/org/rstudio/studio/client/RStudio.java
  src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java
Labels: accessibility

#5921 Fix disconnect between Shiny viewer type and associated pref
  src/cpp/session/modules/SessionErrors.cpp
  src/cpp/session/modules/SessionPlumberViewer.cpp
  src/cpp/session/modules/SessionShinyViewer.cpp
  src/cpp/session/prefs/Preferences.cpp
  src/cpp/tests/testthat/test-shiny.R
Labels: shiny, user preferences

#5919 Make console max line limit configurable
  NEWS.md
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/modules/SessionConsole.cpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Labels: console

#5925 reduce chances of duplicate terminal prompt with complex dynamic prompt
  src/cpp/core/include/core/terminal/PrivateCommand.hpp
Labels: terminal

#5929 associate label with text area in ShowPublicKeyDialog
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/studio/client/common/vcs/CreateKeyDialog.java
  src/gwt/src/org/rstudio/studio/client/common/vcs/ShowPublicKeyDialog.java
Labels: accessibility

#5928 Include count of unsaved files in unsaved files alert dialog
  src/gwt/src/org/rstudio/studio/client/workbench/ui/unsaved/UnsavedChangesDialog.java
Labels: accessibility

#5931 Fix accessibility issues in Shiny Document Warning dialog
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/ShinyDocumentWarning.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/ShinyDocumentWarning.ui.xml
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/ShinyDocumentWarningDialog.java
Labels: accessibility

#5932 Fix assorted visual consistency issues with export plot dialogs
  src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlot.css
  src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlotResources.java
  src/gwt/src/org/rstudio/studio/client/workbench/exportplot/SavePlotAsImageTargetEditor.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/SavePlotAsPdfDialog.java
Labels: accessibility

#5934 Associate labels and controls in Rmd Options dialog
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdChoiceOption.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdFileOption.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdFloatOption.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdNullableOption.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdStringOption.java
Labels: accessibility

#5938 Annotate and associate tabpanel with controlling tabs in RmdTemplateOptions dialog
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateOptionsWidget.java
Labels: accessibility

#5935 Show AppCommand's Id when "nobody was listening"
  src/gwt/src/org/rstudio/core/client/command/AppCommand.java
Labels: workbench

#5939 Provide aria-label for toolbar buttons whose labels are hidden
  src/gwt/src/org/rstudio/core/client/widget/ToolbarButton.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
Labels: accessibility
