Repository rstudio/rstudio, pull requests merged in 2020-12, with the labels that each got.

#8496 fixup C++ multi-line comment behaviors
  src/gwt/acesupport/acemode/c_cpp_style_behaviour.js
Labels: c++

#8503 clear history search offset on new search requests
  NEWS.md
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HistoryCompletionManager.java
Labels: console

#8525 fix opening external files on Big Sur with spaces in filename or path
  NEWS.md
  src/cpp/desktop/DesktopGwtCallback.cpp
Labels: files pane, macos

#8528 Ensure that VirtualConsole ranges don't write outside of VirtualScroller buckets
  src/gwt/src/org/rstudio/core/client/VirtualConsole.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/ConsolePreferencesPane.java
Labels: console

#8522 check for rstudio pam profile on load
  src/cpp/server/ServerMain.cpp
Labels: developer

#8530 Add "rename" command to document tab context menu
  NEWS-1.4-juliet-rose.md
  src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
Labels: enhancement, source editor

#8542 Fix scroll/focus issue in visual editor in non-Chrome browsers
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Labels: ace, visual markdown editing

#8548 encrypt passwords for remote desktop sessions
  src/gwt/src/org/rstudio/studio/client/common/crypto/RSAEncrypt.java
Labels: desktop

#8553 don't quote option completions
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
Labels: autocompletion

#8554 try reloading the IDE main page if the first attempts fail
  src/cpp/desktop/DesktopMainWindow.cpp
  src/cpp/desktop/DesktopMainWindow.hpp
Labels: desktop

#8565 convert condition messages to UTF-8 when handling in notebook
  NEWS-1.4-juliet-rose.md
  src/cpp/r/RExec.cpp
  src/cpp/r/RSourceManager.cpp
  src/cpp/r/RUtil.cpp
  src/cpp/r/include/r/RExec.hpp
  src/cpp/r/include/r/RUtil.hpp
  src/cpp/session/modules/NotebookConditions.R
  src/cpp/session/modules/SessionRUtil.cpp
  src/cpp/session/modules/rmarkdown/NotebookConditions.cpp
  src/cpp/session/modules/rmarkdown/NotebookExec.cpp
Labels: encoding

#8591 rebuild compilation database when compiler changes
  src/cpp/core/libclang/SourceIndex.cpp
  src/cpp/session/modules/clang/RCompilationDatabase.cpp
  src/cpp/session/modules/clang/RCompilationDatabase.hpp
Labels: c++

#8570 also use tinytex when compiling .Rnw-generated .tex files
  src/cpp/session/modules/tex/SessionCompilePdf.cpp
Labels: sweave

#8595 Update openssl on Windows to v1.1.1i
  NEWS-1.4-juliet-rose.md
  dependencies/windows/install-dependencies.cmd
  dependencies/windows/install-openssl/install-openssl.R
  src/cpp/CMakeLists.txt
Labels: developer

#8596 Respect "tab key always moves focus" pref in visual editor
  NEWS-1.4-juliet-rose.md
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Labels: accessibility, visual markdown editing

#8602 Implement previous/following chunk execution commands outside chunks
  NEWS-1.4-juliet-rose.md
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunks.java
Labels: backlog, visual markdown editing

#8650 Fix stale daily build links for MacOS
  docker/jenkins/publish-daily-binary.sh
Labels: builds, developer

#8662 Fix default folder for per-user install on WIndows
  NEWS-1.4-juliet-rose.md
  package/win32/cmake/modules/NSIS.template.in
Labels: packaging, windows
