Repository rstudio/rstudio, pull requests merged in 2020-11, with the labels that each got.

#8269 don't display help for file completion items
  src/cpp/session/modules/SessionHelp.R
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpStrategy.java
Labels: autocompletion

#8292 Avoid intermittent hang on visual editor close
  src/gwt/panmirror/src/editor/src/optional/ace/ace-render-queue.ts
Labels: visual markdown editing

#8272 Fix an issue where the Sqlite DB is corrupted by writing to a stale file handle
  src/cpp/monitor/MonitorClient.cpp
  src/cpp/server/ServerMain.cpp
  src/cpp/shared_core/FileLogDestination.cpp
  src/cpp/shared_core/Logger.cpp
  src/cpp/shared_core/StderrLogDestination.cpp
  src/cpp/shared_core/include/shared_core/FileLogDestination.hpp
  src/cpp/shared_core/include/shared_core/ILogDestination.hpp
  src/cpp/shared_core/include/shared_core/Logger.hpp
  src/cpp/shared_core/include/shared_core/StderrLogDestination.hpp
  src/cpp/shared_core/include/shared_core/system/SyslogDestination.hpp
  src/cpp/shared_core/system/SyslogDestination.cpp
Labels: shared_core

#8267 Verify connection state of PostgreSQL connection pooled connection and re-establish if necessary
  src/cpp/core/Database.cpp
  src/cpp/core/include/core/Database.hpp
Labels: internal database

#8294 fix offset check when reading history
  src/gwt/src/org/rstudio/studio/client/common/CommandLineHistory.java
Labels: console

#8304 scroll cursor into view only after render
  src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
Labels: ace

#8311 Fix Close All Except Current with unsaved files
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Labels: source columns, workbench

#8312 remove duplicate copy of HasContextMenuHandlers interface
  src/gwt/src/org/rstudio/core/client/events/HasContextMenuHandlers.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
Labels: developer

#8325 specify formula switch in brew list invocations
  dependencies/osx/install-dependencies-osx
Labels: developer

#8309 handle multiline tokens with binary ops
  src/cpp/core/r_util/RTokenizerTests.cpp
  src/cpp/session/modules/SessionDiagnosticsTests.cpp
  src/cpp/session/modules/SessionRParser.cpp
Labels: diagnostics

#8271 force promises in S3 methods table on unload
  src/cpp/session/modules/SessionPackages.R
Labels: r interface

#8334 Fix jumpy scroll/cursor/selection action with large code chunks
  src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
Labels: visual markdown editing

#8364 don't enque client events from forked sessions
  NEWS-1.4-juliet-rose.md
  src/cpp/session/SessionModuleContext.cpp
Labels: r interface

#8342 ensure F1 works for Python help when triggered from console
  src/cpp/session/modules/SessionHelp.R
  src/cpp/session/modules/SessionReticulate.R
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTargetWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionManager.java
Labels: python

#8179 implement python auto-outdent
  src/gwt/acesupport/acemode/python.js
Labels: python

#8381 exclude context completions when retrieving chunk option completions
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java
Labels: r markdown

#8380 ensure focus set on file.edit call
  src/cpp/session/modules/SessionSource.R
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Labels: r interface

#8402 fix usage of addHistory flag
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
Labels: console

#8431 Prevent extra untitled doc
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
Labels: workbench

#8432 provide an internal API for closing all source tabs without saving
  src/cpp/r/R/Api.R
  src/cpp/session/SessionClientEvent.cpp
  src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp
  src/cpp/session/modules/SessionSource.cpp
  src/gwt/src/org/rstudio/studio/client/server/model/DocumentCloseAllNoSaveEvent.java
  src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java
  src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Labels: automation

#8430 fix precedence in null check
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Labels: source editor

#8433 use UTF-8 strings in a few more places
  src/cpp/r/RSexp.cpp
  src/cpp/r/include/r/RExec.hpp
  src/cpp/r/include/r/RSexp.hpp
  src/cpp/session/modules/SessionObjectExplorer.cpp
  src/cpp/session/modules/SessionRMarkdown.R
  src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
  src/cpp/session/projects/SessionProjects.cpp
Labels: session internals

#8426 fix regression in completion of methods attached to list objects
  src/cpp/session/modules/SessionRCompletions.R
Labels: autocompletion

#8436 revert to creating strings in native encoding by default
  src/cpp/r/RSexp.cpp
  src/cpp/session/modules/rmarkdown/NotebookQueueUnit.cpp
Labels: encoding, windows

#8440 fix closeAllSourceBuffersWithoutSaving to silently close modified unsaved buffers
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Labels: automation

#8447 Fix Inconsistent Emoji Spacing
  src/gwt/panmirror/src/editor/src/api/emojis-all.ts
  src/gwt/panmirror/src/editor/src/behaviors/insert_symbol/insert_symbol-emoji-skintone.tsx
  src/gwt/panmirror/src/editor/src/behaviors/insert_symbol/insert_symbol-grid-cell.tsx
  src/gwt/panmirror/src/editor/src/editor/editor-theme.ts
  src/gwt/panmirror/src/editor/src/marks/emoji/emoji-completion.tsx
  src/gwt/panmirror/src/editor/src/marks/emoji/emoji.ts
  src/gwt/panmirror/src/editor/tools/generate-symbols.ts
Labels: triage, visual markdown editing

#8449 mark UTF-8 encoding in package_skeleton
  src/cpp/session/modules/SessionPackages.R
Labels: r interface
