Repository rstudio/rstudio, pull requests merged in 2020-04, with the labels that each got.

#6572 use single quotes to escape strings for shell
  src/cpp/core/system/PosixShellUtils.cpp
  src/cpp/core/system/PosixShellUtilsTests.cpp
Labels: session internals

#6539 add support for ragg renderer
  src/cpp/r/RExec.cpp
  src/cpp/r/include/r/session/RGraphics.hpp
  src/cpp/r/session/graphics/RGraphicsUtils.cpp
  src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/modules/SessionGraphics.R
  src/cpp/session/resources/dependencies/r-packages.json
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Labels: plots

#6571 force software rendering when using nouveau driver w/ older Qt
  src/cpp/desktop/DesktopMain.cpp
Labels: desktop integration

#6577 Update dark themes based on the new default node-selector color
  src/cpp/session/resources/themes/README.md
  src/cpp/session/resources/themes/ambiance.rstheme
  src/cpp/session/resources/themes/chaos.rstheme
  src/cpp/session/resources/themes/clouds_midnight.rstheme
  src/cpp/session/resources/themes/cobalt.rstheme
  src/cpp/session/resources/themes/dracula.rstheme
  src/cpp/session/resources/themes/gob.rstheme
  src/cpp/session/resources/themes/idle_fingers.rstheme
  src/cpp/session/resources/themes/kr_theme.rstheme
  src/cpp/session/resources/themes/material.rstheme
  src/cpp/session/resources/themes/merbivore.rstheme
  src/cpp/session/resources/themes/merbivore_soft.rstheme
  src/cpp/session/resources/themes/mono_industrial.rstheme
  src/cpp/session/resources/themes/monokai.rstheme
  src/cpp/session/resources/themes/pastel_on_dark.rstheme
  src/cpp/session/resources/themes/solarized_dark.rstheme
  src/cpp/session/resources/themes/tomorrow_night.rstheme
  src/cpp/session/resources/themes/tomorrow_night_blue.rstheme
  src/cpp/session/resources/themes/tomorrow_night_bright.rstheme
  src/cpp/session/resources/themes/tomorrow_night_eighties.rstheme
  src/cpp/session/resources/themes/twilight.rstheme
  src/cpp/session/resources/themes/vibrant_ink.rstheme
  src/gwt/tools/sync-ace-commits
Labels: themes

#6590 fix C++ warnings related to raw literals and unused parameters
  src/cpp/desktop/DesktopBrowserWindow.cpp
  src/cpp/desktop/DesktopGwtCallbackMac.mm
  src/cpp/session/SessionModuleContext.cpp
  src/cpp/session/modules/build/SessionBuild.cpp
Labels: developer

#6591 cleanup (some) deprecated Qt usage
  src/cpp/desktop/CMakeLists.txt
  src/cpp/desktop/DesktopMain.cpp
  src/cpp/desktop/DesktopOptions.cpp
  src/cpp/desktop/DesktopRVersion.cpp
Labels: desktop, developer

#6592 Implement custom fonts for RStudio Server
  NEWS.md
  package/linux/debian-control/postinst.in
  package/linux/rpm-script/postinst.sh.in
  src/cpp/server/CMakeLists.txt
  src/cpp/server/ServerMain.cpp
  src/cpp/server/fonts/README.md
  src/cpp/session/CMakeLists.txt
  src/cpp/session/SessionClientInit.cpp
  src/cpp/session/SessionMain.cpp
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/modules/SessionFonts.cpp
  src/cpp/session/modules/SessionFonts.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/cpp/session/resources/themes/css/fonts.css
  src/cpp/shared_core/FilePath.cpp
  src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.css
  src/gwt/src/org/rstudio/core/client/theme/RStudioCellTableStyle.css
  src/gwt/src/org/rstudio/core/client/theme/RStudioDataGridStyle.css
  src/gwt/src/org/rstudio/core/client/theme/ThemeFonts.java
  src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
  src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
  src/gwt/src/org/rstudio/studio/client/common/sourcemarkers/SourceMarkerItemCodec.java
  src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AceEditorPreview.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/model/ThemeServerOperations.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java
Labels: workbench

#6599 Restore project if it starts successfully
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/projects/SessionProjects.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Labels: projects

#6602 Fix some windows-only compilation warnings
  src/cpp/session/modules/SessionFind.cpp
  src/cpp/session/modules/SessionRParser.cpp
  src/cpp/shared_core/include/shared_core/ReaderWriterMutex.hpp
  src/cpp/shared_core/json/Json.cpp
Labels: developer

#6600 fix handling of single quotes in download option
  src/cpp/session/modules/SessionCodeTools.R
  src/cpp/tests/testthat/test-codetools.R
Labels: publishing

#6598 improve handling of UNC paths on Windows
  src/cpp/core/FilePathTests.cpp
  src/cpp/shared_core/FilePath.cpp
Labels: shared_core

#6428 Hide any tab from view
  NEWS.md
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/core/client/layout/DualWindowLayoutPanel.java
  src/gwt/src/org/rstudio/core/client/layout/LogicalWindow.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneConfig.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchTabPanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionsPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsolePane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/history/view/HistoryPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/plots/PlotsPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java
Labels: workbench

#6578 disable focus on hover for cpp completions
  NEWS.md
  src/gwt/src/org/rstudio/core/client/widget/ScrollableToolbarPopupMenu.java
Labels: source editor

#6606 further refine Ace behavior in shell widget
  src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Labels: ace

#6609 remove hard-coded console shortcuts
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
Labels: ace, keyboard shortcuts

#6611 move client app event handler interfaces into event classes
  src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
  src/gwt/src/org/rstudio/studio/client/application/DesktopHooks.java
  src/gwt/src/org/rstudio/studio/client/application/events/ApplicationEventHandlers.java
  src/gwt/src/org/rstudio/studio/client/application/events/ApplicationVisibilityChangedEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/ChangeFontSizeEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/ChangeFontSizeHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/ClientDisconnectedEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/ClientDisconnectedHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/CrossWindowEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/DeferredInitCompletedEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/FileUploadEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/FileUploadHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/HandleUnsavedChangesEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/HandleUnsavedChangesHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/InterruptStatusEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/InvalidClientVersionEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/InvalidClientVersionHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/InvalidSessionEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/LogoutRequestedEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/LogoutRequestedHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/QuitEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/QuitHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/QuitInitiatedEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/QuitInitiatedHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/RVersionsChangedEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/ReloadEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/ReloadWithLastChanceSaveEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/ResetEditorCommandsEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/RestartStatusEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/SaveActionChangedEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/SaveActionChangedHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/ServerOfflineEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/ServerOfflineHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/ServerUnavailableEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/ServerUnavailableHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/SessionAbendWarningEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/SessionAbendWarningHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/SessionCountChangedEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/SessionRelaunchEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/SessionRelaunchHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/SessionSerializationEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/SessionSerializationHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/SetEditorCommandBindingsEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/SuicideEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/SuicideHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/SuspendAndRestartEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/SuspendAndRestartHandler.java
  src/gwt/src/org/rstudio/studio/client/application/events/SwitchToRVersionEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/UnauthorizedEvent.java
  src/gwt/src/org/rstudio/studio/client/application/events/UnauthorizedHandler.java
  src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteWindow.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/RmdOutput.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
Labels: developer

#6614 disable JobsListTests GWT unit test due to slowness
  src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
Labels: automation, developer

#6624 Upgrade to Qt 5.12.8
  dependencies/linux/README
  dependencies/linux/install-qt-linux
  dependencies/osx/README
  dependencies/osx/install-qt-macos
  dependencies/windows/Install-RStudio-Prereqs.ps1
  dependencies/windows/README.md
  dependencies/windows/qt-5-12-6.png
  docker/jenkins/Dockerfile.bionic-amd64
  docker/jenkins/Dockerfile.centos7-x86_64
  docker/jenkins/Dockerfile.centos8-x86_64
  docker/jenkins/Dockerfile.debian9-x86_64
  docker/jenkins/Dockerfile.opensuse15-x86_64
  docker/jenkins/Dockerfile.windows
  docker/jenkins/Dockerfile.xenial-amd64
  src/cpp/desktop/CMakeLists.txt
Labels: desktop, developer, qtwebengine

#6630 windows dockerfile tweaks
  docker/jenkins/Dockerfile.windows
Labels: builds, developer, windows

#6640 bug fix for opening large files
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Labels: workbench

#6638 drop desktop support for opensuse/sles 12
  Jenkinsfile
  dependencies/linux/README
  docker/jenkins/Dockerfile.opensuse-x86_64
  src/cpp/desktop/CMakeLists.txt
  src/cpp/desktop/DesktopGwtWindow.cpp
  src/cpp/desktop/DesktopMain.cpp
  src/cpp/desktop/DesktopOptions.cpp
  src/cpp/desktop/DesktopSecondaryWindow.cpp
  src/cpp/desktop/DesktopUtils.cpp
  src/cpp/desktop/DesktopWebView.cpp
Labels: builds

#6634 Fix "Move Focus to Console"
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsolePane.java
Labels: console

#6656 disable themes unit test
  src/cpp/tests/testthat/disabled/test-themes.R
Labels: automation

#6655 remove detection of chromeframe plugin
  src/cpp/core/BrowserUtils.cpp
  src/cpp/core/http/Response.cpp
Labels: developer

#6657 Use test mock font loader; re-enable JobsList tests
  src/gwt/src/org/rstudio/core/Core.gwt.xml
  src/gwt/src/org/rstudio/core/client/theme/ThemeFonts.java
  src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
  src/gwt/src/org/rstudio/studio/RStudioTests.gwt.xml
  src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
Labels: automation, jobs

#6654 remove IE10 support code
  src/gwt/src/org/rstudio/core/Core.gwt.xml
  src/gwt/src/org/rstudio/core/client/BrowseCap.java
  src/gwt/src/org/rstudio/core/client/BrowseCapIE10.java
  src/gwt/src/org/rstudio/core/client/dom/impl/DomUtilsIE10Impl.java
Labels: developer, internet explorer, server

#6658 Sort file names naturally in the Files pane
  NEWS.md
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/core/client/StringUtil.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java
Labels: files pane

#6662 add command to Files Pane More menu to copy path to clipboard
  NEWS.md
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesTab.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileCommandToolbar.java
Labels: files pane

#6588 improve handling of multiline Python blocks in console
  src/cpp/core/StringUtils.cpp
  src/cpp/core/include/core/StringUtils.hpp
  src/cpp/session/SessionConsoleInput.cpp
  src/cpp/tests/python/test-code-submit.py
Labels: console, python

#6669 Ensure RStudio document tabs are reopened on first boot from 1.2 -> 1.3
  src/cpp/session/SessionMain.cpp
  src/cpp/session/include/session/prefs/UserPrefs.hpp
  src/cpp/session/prefs/UserPrefs.cpp
  src/cpp/session/projects/SessionProjectContext.cpp
  src/cpp/session/projects/SessionProjects.cpp
Labels: user preferences

#6680 fix document save for IE11
  NOTICE
  src/gwt/src/org/rstudio/core/client/BrowseCap.java
  src/gwt/src/org/rstudio/core/client/patch/SubstringDiff.java
  src/gwt/src/org/rstudio/core/client/polyfill/FastestSmallestTextEncoderDecoder.java
  src/gwt/src/org/rstudio/core/client/polyfill/js/FastestSmallestTextEncoderDecoder.min.js
  src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
  src/gwt/www/index.htm
  src/gwt/www/js/text.min.js
Labels: internet explorer

#6686 update Rtools URL
  src/cpp/core/r_util/RToolsInfo.cpp
Labels: rtools

#6672 Always refresh data viewer when source data changes
  src/cpp/session/resources/grid/dtviewer.js
  src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTargetWidget.java
Labels: data viewer

#6699 Fix broken themes unit tests
  src/cpp/session/modules/SessionThemes.R
  src/cpp/session/resources/themes/README.md
  src/cpp/session/resources/themes/compile-themes.R
  src/cpp/tests/testthat/regenerate-css.R
  src/cpp/tests/testthat/test-themes.R
  src/cpp/tests/testthat/themes/rsthemes/DebugLine.rstheme
  src/cpp/tests/testthat/themes/rsthemes/active4d.rstheme
  src/cpp/tests/testthat/themes/rsthemes/all_hallows_eve.rstheme
  src/cpp/tests/testthat/themes/rsthemes/amy.rstheme
  src/cpp/tests/testthat/themes/rsthemes/blackboard.rstheme
  src/cpp/tests/testthat/themes/rsthemes/brilliance_black.rstheme
  src/cpp/tests/testthat/themes/rsthemes/brilliance_dull.rstheme
  src/cpp/tests/testthat/themes/rsthemes/chrome_dev_tools.rstheme
  src/cpp/tests/testthat/themes/rsthemes/clouds.rstheme
  src/cpp/tests/testthat/themes/rsthemes/clouds_midnight.rstheme
  src/cpp/tests/testthat/themes/rsthemes/cobalt.rstheme
  src/cpp/tests/testthat/themes/rsthemes/dawn.rstheme
  src/cpp/tests/testthat/themes/rsthemes/dreamweaver.rstheme
  src/cpp/tests/testthat/themes/rsthemes/eiffel.rstheme
  src/cpp/tests/testthat/themes/rsthemes/espresso_libre.rstheme
  src/cpp/tests/testthat/themes/rsthemes/git_hub.rstheme
  src/cpp/tests/testthat/themes/rsthemes/i_plastic.rstheme
  src/cpp/tests/testthat/themes/rsthemes/idle.rstheme
  src/cpp/tests/testthat/themes/rsthemes/idle_fingers.rstheme
  src/cpp/tests/testthat/themes/rsthemes/katzenmilch.rstheme
  src/cpp/tests/testthat/themes/rsthemes/kr_theme.rstheme
  src/cpp/tests/testthat/themes/rsthemes/kuroir_theme.rstheme
  src/cpp/tests/testthat/themes/rsthemes/lazy.rstheme
  src/cpp/tests/testthat/themes/rsthemes/magic_wb_amiga.rstheme
  src/cpp/tests/testthat/themes/rsthemes/merbivore.rstheme
  src/cpp/tests/testthat/themes/rsthemes/merbivore_soft.rstheme
  src/cpp/tests/testthat/themes/rsthemes/mono_industrial.rstheme
  src/cpp/tests/testthat/themes/rsthemes/monokai.rstheme
  src/cpp/tests/testthat/themes/rsthemes/pastels_on_dark.rstheme
  src/cpp/tests/testthat/themes/rsthemes/slush_and_poppies.rstheme
  src/cpp/tests/testthat/themes/rsthemes/solarized_dark.rstheme
  src/cpp/tests/testthat/themes/rsthemes/solarized_light.rstheme
  src/cpp/tests/testthat/themes/rsthemes/sunburst.rstheme
  src/cpp/tests/testthat/themes/rsthemes/textmate.rstheme
  src/cpp/tests/testthat/themes/rsthemes/tomorrow.rstheme
  src/cpp/tests/testthat/themes/rsthemes/tomorrow_night.rstheme
  src/cpp/tests/testthat/themes/rsthemes/tomorrow_night_blue.rstheme
  src/cpp/tests/testthat/themes/rsthemes/tomorrow_night_bright.rstheme
  src/cpp/tests/testthat/themes/rsthemes/tomorrow_night_eighties.rstheme
  src/cpp/tests/testthat/themes/rsthemes/twilight.rstheme
  src/cpp/tests/testthat/themes/rsthemes/vibrant_ink.rstheme
  src/cpp/tests/testthat/themes/rsthemes/xcode_default.rstheme
  src/cpp/tests/testthat/themes/rsthemes/zenburnesque.rstheme
Labels: automation

#6705 Prevent replace exception
  src/cpp/session/modules/SessionFind.cpp
Labels: find in files

#6671 add lt_LT_new to dictionary blacklist
  src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java
Labels: spellcheck

#6712 Change default sqlite database path from /var/run to /var/lib to ensure it is not deleted on reboot
  src/cpp/server/ServerMain.cpp
  src/cpp/server/extras/conf/database.conf
  src/cpp/server_core/ServerDatabase.cpp
  src/cpp/server_core/include/server_core/ServerDatabase.hpp
Labels: internal database

#6688 Show metadata summary for tibbles in R Notebooks
  NEWS.md
  src/cpp/session/modules/NotebookData.R
  src/cpp/session/resources/pagedtable/pagedtable.css
  src/cpp/session/resources/pagedtable/pagedtable.js
  src/gwt/src/org/rstudio/studio/client/rmarkdown/model/NotebookFrameMetadata.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkDataPage.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkDataPreview.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkDataWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
Labels: notebooks

#6716 update RStudio 1.3-patch to Qt 5.12.8
  NEWS-1.3-patch.md
  dependencies/linux/README
  dependencies/linux/install-qt-linux
  dependencies/osx/README
  dependencies/osx/install-qt-macos
  dependencies/windows/Install-RStudio-Prereqs.ps1
  dependencies/windows/README.md
  dependencies/windows/qt-5-12-6.png
  docker/jenkins/Dockerfile.bionic-amd64
  docker/jenkins/Dockerfile.centos7-x86_64
  docker/jenkins/Dockerfile.centos8-x86_64
  docker/jenkins/Dockerfile.debian9-x86_64
  docker/jenkins/Dockerfile.opensuse15-x86_64
  docker/jenkins/Dockerfile.windows
  docker/jenkins/Dockerfile.xenial-amd64
  src/cpp/desktop/CMakeLists.txt
Labels: qtwebengine

#6718 Move URL::test to testthat
  src/cpp/core/http/URL.cpp
  src/cpp/core/http/URLTests.cpp
  src/cpp/core/include/core/http/URL.hpp
Labels: automation

#6725 fix pane max/min behavior
  src/gwt/src/org/rstudio/core/client/theme/WindowFrameButton.java
Labels: workbench

#6722 ensure plot directory before creation
  NEWS.md
  src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp
Labels: plots

#6610 use shebang to infer filetype when appropriate
  src/cpp/session/SessionSourceDatabase.cpp
  src/cpp/session/include/session/SessionSourceDatabase.hpp
  src/cpp/session/modules/SessionRUtil.cpp
  src/cpp/session/modules/SessionSource.cpp
  src/cpp/session/modules/customsource/SessionCustomSource.cpp
  src/cpp/session/modules/preview/SessionPreview.cpp
  src/cpp/session/modules/rmarkdown/NotebookCache.cpp
Labels: source editor

#6529 use versioned project name
  CMakeGlobals.txt
  CMakeLists.txt
  CMakeRelease.txt
  RELEASE
  src/cpp/CMakeLists.txt
Labels: developer

#6733 fix ensure visible behavior
  src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
  src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Labels: ace, console

#6744 Use separate state files for desktop and server
  src/cpp/diagnostics/DiagnosticsMain.cpp
  src/cpp/session/include/session/prefs/UserState.hpp
  src/cpp/session/prefs/UserStateLayer.cpp
Labels: session internals

#6745 Sync publish path even when type has not changed
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Labels: publishing

#6738 prevent double-click from triggering weird panel behavior
  src/gwt/src/org/rstudio/core/client/theme/WindowFrameButton.java
Labels: workbench

#6749 Do not attempt to read device list after error
  src/cpp/session/modules/rmarkdown/NotebookPlots.cpp
Labels: notebooks, plots

#6752 Fix SessionFind tests on Windows
  src/cpp/session/modules/SessionFindTests.cpp
Labels: find in files

#6759 Read old RStudio 1.3 state file if it exists
  src/cpp/session/prefs/UserStateLayer.cpp
  src/cpp/session/prefs/UserStateLayer.hpp
Labels: user preferences

#6753 work around IE CSS styling issue
  src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
Labels: internet explorer

#6758 Script for local Docker-based Windows builds
  docker/win-docker-compile.cmd
Labels: builds, developer

#6764 Add toggle for soft wrap mode
  NEWS.md
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/studio/client/common/filetypes/RWebContentFileType.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/EditSession.java
Labels: source editor

#6766 tweak win-docker-compile script to also work with Desktop Pro building
  docker/win-docker-compile.cmd
Labels: builds, developer

#6776 Allow for package dependency discovery in untitled buffers
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Labels: diagnostics

#6778 enable wordwrap and selection of message in RSA key creation error dialog
  src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
  src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
  src/gwt/src/org/rstudio/core/client/widget/ShowContentDialog.java
Labels: vcs

#6765 Callback for rstudioapi::highlightUi
  src/gwt/src/org/rstudio/core/client/events/HighlightEvent.java
  src/gwt/src/org/rstudio/studio/client/workbench/UserInterfaceHighlighter.java
Labels: rstudioapi

#6774 Remove old application agreement feature
  src/cpp/session/CMakeLists.txt
  src/cpp/session/SessionClientInit.cpp
  src/cpp/session/SessionMain.cpp
  src/cpp/session/SessionOptions.cpp
  src/cpp/session/include/session/SessionOptions.hpp
  src/cpp/session/include/session/prefs/UserStateValues.hpp
  src/cpp/session/modules/SessionAgreement.cpp
  src/cpp/session/modules/SessionAgreement.hpp
  src/cpp/session/modules/SessionUserPrefsMigration.cpp
  src/cpp/session/prefs/UserStateValues.cpp
  src/cpp/session/resources/schema/user-state-schema.json
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/application/ApplicationView.java
  src/gwt/src/org/rstudio/studio/client/application/model/ApplicationServerOperations.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationAgreementDialog.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
  src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/model/Agreement.java
  src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
Labels: workbench
