Repository rstudio/rstudio, pull requests merged in 2020-03, with the labels that each got.

#6370 round computed number of rows for line widgets
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/ace-uncompressed.js
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/ace.js
Labels: ace

#6355 Ensure packages are installed in correct order to eliminate duplication
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/modules/SessionDependencies.R
  src/cpp/session/modules/SessionDependencies.cpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/cpp/tests/testthat/test-dependencies.R
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Labels: r packages

#6409 simplify screen reader toggle shortcut
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/www/docs/keyboard.htm
Labels: accessibility

#6416 check for null pointers in shadowDevOff
  src/cpp/r/RExec.cpp
  src/cpp/r/session/graphics/RGraphicsDevice.cpp
  src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp
Labels: r interface

#6401 share web profile across different pages
  src/cpp/desktop/DesktopWebProfile.cpp
Labels: qtwebengine

#6405 avoid passing user input to printf format strings
  src/cpp/r/session/RInit.cpp
  src/cpp/r/session/RQuit.cpp
  src/cpp/r/session/RSearchPath.cpp
  src/cpp/r/session/RSession.cpp
  src/cpp/r/session/RSessionState.cpp
  src/cpp/r/session/RStdCallbacks.cpp
  src/cpp/r/session/graphics/RGraphicsDevice.cpp
  src/cpp/r/session/graphics/RGraphicsUtils.cpp
  src/cpp/session/SessionMain.cpp
Labels: r interface

#6408 use .rs.addFunction uniformly
  src/cpp/r/R/Tools.R
  src/cpp/session/SessionMain.cpp
  src/cpp/session/modules/SessionCompletionHooks.R
Labels: r interface

#6415 refine instructions for installing Qt 5.12.6 on Windows
  dependencies/windows/README.md
  dependencies/windows/qt-5-12-6.png
Labels: builds, documentation

#6417 Fix inability to change default R version
  src/gwt/src/org/rstudio/studio/client/application/ui/RVersionSelectWidget.java
Labels: r versions

#6420 tutorials depend on rstudioapi
  src/cpp/session/resources/dependencies/r-packages.json
Labels: tutorials

#6419 disable indented soft wrap
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
Labels: ace

#6422 fix regression with right-click pasting into console on RStudio Desktop
  src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java
  src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
  src/gwt/test/org/rstudio/core/client/ConsoleOutputWriterTests.java
Labels: accessibility, console

#6431 simplify several accessibility-related shortcuts
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/www/docs/keyboard.htm
Labels: accessibility

#6434 use dependency manager for tutorial dependencies
  src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java
Labels: tutorials

#6436 fix regression in update packages dialog
  src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackageActionConfirmationDialog.java
Labels: packages pane

#6439 Allow same origin for Tutorial pane sandbox
  src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java
Labels: tutorials

#6442 Reduce disruptions caused by autosave
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Labels: source editor

#6448 change toggle screenreader shortcut on Mac to avoid clash with intl keyboards
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/www/docs/keyboard.htm
Labels: accessibility

#6443 tutorial pane bugfixes
  src/cpp/session/modules/SessionTutorial.R
  src/gwt/src/org/rstudio/studio/client/common/DefaultGlobalDisplay.java
  src/gwt/src/org/rstudio/studio/client/common/GlobalDisplay.java
  src/gwt/src/org/rstudio/studio/client/common/impl/WebWindowOpener.java
  src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialServerOperations.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialUtil.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/events/TutorialCommandEvent.java
Labels: tutorials

#6449 Maintain file permissions while performing replace
  src/cpp/session/modules/SessionFind.cpp
Labels: find in files

#6463 Match realtime and not realtime token predicates, allow missing aff files
  src/cpp/session/modules/SessionSpelling.cpp
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/spelling/CheckSpelling.java
Labels: spellcheck

#6450 speculative fix for writeToPNG errors
  src/cpp/r/session/graphics/RGraphicsPlot.cpp
Labels: r interface

#6466 avoid using deparse when checking call
  src/cpp/session/modules/SessionErrors.R
Labels: r interface

#6468 port Ace patch for wrapped line rendering
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/ace-uncompressed.js
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/ace.js
Labels: ace

#6488 fix diagnostics report for Windows
  src/cpp/r/R/Diagnostics.R
Labels: diagnostics

#6492 check for fork in package event callbacks
  NEWS.md
  src/cpp/session/SessionModuleContext.cpp
Labels: r interface

#6510 refresh potentially stale viewer fn definitions
  src/cpp/session/modules/SessionShinyViewer.R
  src/cpp/session/modules/SessionShinyViewer.cpp
Labels: shiny

#6506 acknowledgments in NEWS
  NEWS-1.3.md
Labels: documentation

#6517 opt-in to Qt AltGr detection
  src/cpp/desktop/DesktopMain.cpp
Labels: desktop, windows

#6503 make global VCS commands rebindable
  src/gwt/.gitignore
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Labels: qtwebengine

#6525 invoke renv::init() in subproc
  src/cpp/session/modules/SessionRenv.R
Labels: renv

#6521 Fix bug where replace errors did not appear with the correct file
  src/cpp/session/modules/SessionFind.cpp
Labels: find in files

#6531 add menu access key to rename in scope command
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Labels: accessibility

#6520 allow configuring graphics device type, antialias
  src/cpp/r/R/Tools.R
  src/cpp/r/include/r/session/RGraphics.hpp
  src/cpp/r/include/r/session/RGraphicsConstants.h
  src/cpp/r/session/graphics/RGraphicsUtils.cpp
  src/cpp/session/CMakeLists.txt
  src/cpp/session/SessionClientInit.cpp
  src/cpp/session/SessionMain.cpp
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/modules/SessionGraphics.R
  src/cpp/session/modules/SessionGraphics.cpp
  src/cpp/session/modules/SessionGraphics.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Labels: plots

#6556 fix scroll for multiline console input
  src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Labels: console

#6554 Switch away from Jobs pane after successful package installation
  src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
Labels: jobs

#6557 force clang-darwin toolset when building boost on macOS
  dependencies/common/install-boost
Labels: developer

#6567 backport new qt install technique to 1.2 patch
  dependencies/common/install-qt.sh
  dependencies/linux/install-qt-linux
  dependencies/osx/install-dependencies-osx
  dependencies/osx/install-qt-macos
  docker/jenkins/Dockerfile.bionic-amd64
  docker/jenkins/Dockerfile.centos7-x86_64
  docker/jenkins/Dockerfile.debian9-x86_64
  docker/jenkins/Dockerfile.fedora28-x86_64
  docker/jenkins/Dockerfile.opensuse15-x86_64
  docker/jenkins/Dockerfile.xenial-amd64
Labels: builds

#6562 refine editing behavior in multi-line console
  src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
  src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/Renderer.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/ace-uncompressed.js
Labels: console
