Repository rstudio/rstudio, pull requests merged in 2020-05, with the labels that each got.

#6787 Add class attributes to chunks
  src/gwt/src/org/rstudio/core/client/StringUtil.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetChunks.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextToolbar.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextUi.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkOutputUi.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/DefaultChunkOptionsPopupPanel.java
  src/gwt/test/org/rstudio/core/client/StringUtilTests.java
  src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
  src/gwt/test/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextUiTests.java
Labels: r markdown, rstudioapi

#6793 Make highlights more noticeable
  src/gwt/src/org/rstudio/studio/client/workbench/UserInterfaceHighlighter.css
  src/gwt/src/org/rstudio/studio/client/workbench/UserInterfaceHighlighter.java
Labels: rstudioapi

#6804 Fix HTML widget viewing on R 4.0 for Windows
  src/cpp/session/SessionModuleContext.cpp
  src/cpp/session/modules/SessionHelp.cpp
  src/cpp/session/modules/viewer/SessionViewer.cpp
Labels: viewer pane, windows

#6807 Restore correct element ID for console's input field
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Labels: console, rstudioapi

#6828 Fix coexistence of git for windows and rtools4
  NEWS-1.3-patch.md
  src/cpp/session/modules/SessionTerminalShell.cpp
Labels: desktop, terminal, windows

#6827 avoid setting null pointer on R_tryEval error
  src/cpp/r/RExec.cpp
  src/cpp/session/modules/SessionRTests.cpp
Labels: r interface

#6832 Add unique rstudio_foo classes to some source panel elements
  src/gwt/src/org/rstudio/core/client/ClassIds.java
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
  src/gwt/src/org/rstudio/core/client/theme/MinimizedWindowFrame.java
  src/gwt/src/org/rstudio/core/client/theme/WindowFrame.java
  src/gwt/src/org/rstudio/core/client/theme/WindowFrameButton.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.java
Labels: automation, rstudio.cloud

#6844 Install correct Qt libs on Linux
  dependencies/common/install-qt.sh
  dependencies/linux/install-qt-linux
Labels: builds, desktop, linux, qtwebengine

#6851 Add common statistics terminology to spell checker
  src/gwt/src/org/rstudio/studio/client/common/spelling/domain_specific_words.csv
Labels: spellcheck

#6841 Fix issue with global replace
  src/cpp/session/modules/SessionFind.cpp
  src/cpp/session/modules/SessionFind.hpp
  src/cpp/session/modules/SessionFindTests.cpp
Labels: find in files

#6853 defend against 'undefined' ch at boundary of string
  src/gwt/src/org/rstudio/core/client/patch/SubstringDiff.java
Labels: source editor

#6857 add additional keyboard shortcut for Focus Console Output command
  NEWS-1.3-patch.md
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/www/docs/keyboard.htm
Labels: accessibility, keyboard shortcuts

#6860 remove unimplemented Search History command entry
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/history/History.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/history/HistoryTab.java
Labels: developer

#6848 Add RStudio Command Palette
  NEWS.md
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/SafeHtmlUtil.java
  src/gwt/src/org/rstudio/core/client/a11y/A11y.java
  src/gwt/src/org/rstudio/core/client/command/AppCommand.java
  src/gwt/src/org/rstudio/core/client/command/KeyCombination.java
  src/gwt/src/org/rstudio/core/client/widget/FullscreenPopupPanel.java
  src/gwt/src/org/rstudio/core/client/widget/ModalPopupPanel.java
  src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AppCommandPaletteEntry.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
  src/gwt/src/org/rstudio/studio/client/application/ui/CommandPalette.java
  src/gwt/src/org/rstudio/studio/client/application/ui/CommandPalette.ui.xml
  src/gwt/src/org/rstudio/studio/client/application/ui/CommandPaletteEntry.java
  src/gwt/src/org/rstudio/studio/client/application/ui/CommandPaletteEntry.ui.xml
  src/gwt/src/org/rstudio/studio/client/application/ui/CommandPaletteLauncher.java
  src/gwt/src/org/rstudio/studio/client/application/ui/RAddinCommandPaletteEntry.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/test/org/rstudio/core/client/SafeHtmlUtilTests.java
  src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
Labels: command palette

#6849 Rework Source structure
  src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
  src/gwt/src/org/rstudio/studio/client/application/DesktopHooks.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/RmdOutput.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/Prefs.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserState.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceBuildHelper.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceSatellitePresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceSatelliteWindow.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceShim.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindow.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPresenter.java
  src/gwt/tools/prefs/UserStateAccessor.java
Labels: source editor, workbench

#6875 Improve command palette UX for disabled commands
  src/gwt/src/org/rstudio/core/client/command/AppCommand.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AppCommandPaletteEntry.java
  src/gwt/src/org/rstudio/studio/client/application/ui/CommandPalette.java
  src/gwt/src/org/rstudio/studio/client/application/ui/CommandPaletteEntry.java
  src/gwt/src/org/rstudio/studio/client/application/ui/CommandPaletteEntry.ui.xml
  src/gwt/src/org/rstudio/studio/client/application/ui/RAddinCommandPaletteEntry.java
Labels: command palette

#6876 use html5 header element instead of role=banner
  src/gwt/src/org/rstudio/core/client/widget/BannerWidget.java
Labels: accessibility

#6880 Apply themed font to history and VCS panes
  src/gwt/src/org/rstudio/studio/client/workbench/views/history/view/HistoryTable.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/diff/LineTableView.java
Labels: workbench

#6885 Use system config alone when user config is missing
  src/cpp/session/modules/SessionConfigFile.cpp
Labels: user preferences

#6889 fix cpp unit tests on macos
  dependencies/osx/install-dependencies-osx
  src/cpp/rstudio-tests.in
Labels: automation, developer, macos

#6906 Work around R bug in function deparse
  src/cpp/session/modules/SessionCodeTools.R
  src/cpp/tests/testthat/test-environment.R
Labels: debugging

#6914 ensure Ace loaded before initializing command manager
  src/gwt/src/org/rstudio/core/client/command/EditorCommandManager.java
Labels: ace

#6916 always set role=application on entire page and remove user option
  NEWS-1.3-patch.md
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteApplication.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java
Labels: accessibility

#6933 ignore .snapshot files when creating notebook
  src/cpp/session/modules/SessionRmdNotebook.R
Labels: notebooks

#6947 fix startup timing issue with enabling console announcements
  src/gwt/src/org/rstudio/core/client/VirtualConsole.java
  src/gwt/src/org/rstudio/core/client/command/ShortcutViewer.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/events/ScreenReaderStateReadyEvent.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
Labels: accessibility

#6952 allow enter key to click active button in web dialogs
  src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
Labels: accessibility

#6956 set document role on focusable console output spans
  src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java
Labels: accessibility, jaws

#6964 fix inverted logic for enabling/disabling warning bar announcements
  NEWS-1.3-patch.md
  src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java
Labels: accessibility

#6966 pause a bit before updating infobar status text so JAWS sees the change
  src/gwt/src/org/rstudio/core/client/widget/InfoBar.java
  src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
  src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java
Labels: accessibility

#6980 ensure masked function objects are resolved correctly
  src/cpp/session/modules/SessionCodeTools.R
  src/cpp/session/modules/SessionRCompletions.R
Labels: autocompletion

#6990 Only set R_LIBS_SITE if it is not empty
  NEWS-1.3-patch.md
  src/cpp/core/include/core/r_util/RVersionsPosix.hpp
Labels: r interface

#6991 fix function lookup for objects on search path not within namespace
  src/cpp/session/modules/SessionCodeTools.R
Labels: autocompletion

#6993 Add command for going to server home (pro-only)
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/loadServerHome.png
  src/gwt/src/org/rstudio/studio/client/workbench/commands/loadServerHome_2x.png
Labels: accessibility, server, workbench

#6976 cpp completion manager needs to explicitly handle keys
  src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionPopupMenu.java
Labels: autocompletion

#6994 don't use key property for older Qt
  src/gwt/src/org/rstudio/core/client/BrowseCap.java
  src/gwt/src/org/rstudio/core/client/Version.java
  src/gwt/src/org/rstudio/core/client/command/KeyCombination.java
Labels: qtwebengine

#6992 Update shinytest folder location
  src/cpp/session/modules/SessionTests.R
  src/cpp/session/modules/build/SessionBuild.cpp
Labels: shiny

#7006 handle raw strings in backend tokenizer
  src/cpp/core/include/core/r_util/RTokenizer.hpp
  src/cpp/core/r_util/RTokenizer.cpp
  src/cpp/core/r_util/RTokenizerTests.cpp
Labels: diagnostics
