Repository rstudio/rstudio, pull requests merged in 2020-01, with the labels that each got.

#5942 cleanup static HTML for accessibility, valid HTML
  src/cpp/desktop/html/connect.html
  src/cpp/desktop/html/error.html
  src/gwt/www/404.htm
  src/gwt/www/error.htm
  src/gwt/www/expired.htm
  src/gwt/www/offline.htm
  src/gwt/www/progress.htm
  src/gwt/www/projectnotfound.htm
  src/gwt/www/unsupported_browser.htm
Labels: accessibility

#5947 associate labels and controls in NewRdDialog
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRdDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRdDialog.ui.xml
Labels: accessibility

#5946 Fix accessibility of job-quit-warning dialog
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobQuitControls.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobQuitControls.ui.xml
Labels: accessibility

#5940 Prevent duplicate element IDs when multiple source files are open
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Labels: accessibility

#5949 associate labels with listbox controls in New RMarkdown dialog
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/widget/CaptionWithHelp.java
  src/gwt/src/org/rstudio/core/client/widget/WidgetListBox.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.java
Labels: accessibility

#5922 Update RCNTXT copy for R 4.0
  src/cpp/r/RCntxt.cpp
  src/cpp/r/RCntxtUtils.cpp
  src/cpp/r/include/r/RCntxtUtils.hpp
  src/cpp/r/include/r/RInterface.hpp
Labels: debugging

#5943 option to show only project name instead of full path in desktop window title
  NEWS.md
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/studio/client/application/DesktopHooks.java
  src/gwt/src/org/rstudio/studio/client/workbench/WorkbenchContext.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Labels: desktop

#5952 Fix basic accessibility issues with RSConnect / RPubs dialogs / wizards
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/widget/FormLabel.java
  src/gwt/src/org/rstudio/core/client/widget/TextBoxWithCue.java
  src/gwt/src/org/rstudio/studio/client/common/rpubs/ui/RPubsUploadDialog.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectAccountList.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.ui.xml
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectLocalAccount.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectLocalAccount.ui.xml
Labels: accessibility

#5955 add aria-label to textarea in ShinyApps.Io connection dialog
  src/gwt/src/org/rstudio/core/client/widget/FormTextArea.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectCloudAccount.ui.xml
Labels: accessibility

#5957 Make LeftRightToggleButton accessible using html buttons and aria-pressed
  src/gwt/src/org/rstudio/core/client/widget/LeftRightToggleButton.css
  src/gwt/src/org/rstudio/core/client/widget/LeftRightToggleButton.java
  src/gwt/src/org/rstudio/core/client/widget/LeftRightToggleButton.ui.xml
Labels: accessibility

#5959 Fix excessive CPU usage in pathological R session closure
  src/cpp/session/SessionModuleContext.cpp
  src/cpp/session/include/session/SessionModuleContext.hpp
  src/cpp/session/modules/SessionFilesListingMonitor.cpp
  src/cpp/session/projects/SessionProjectContext.cpp
  src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/ExistingDirectoryPage.java
Labels: projects

#5962 bump hardcoded copyright dates in code templates and NSIS template
  package/win32/cmake/modules/NSIS.template.in
  src/cpp/tools/editor-settings/qt-license-template.txt
  src/gwt/tools/editor-settings/codetemplates.xml
  src/gwt/tools/editor-settings/eclipse-templates.xml
Labels: developer

#5965 add uniqueIds for TextBoxWithButton widgets
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/widget/DirectoryChooserTextBox.java
  src/gwt/src/org/rstudio/core/client/widget/FileChooserTextBox.java
  src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
  src/gwt/src/org/rstudio/studio/client/common/vcs/ignore/IgnoreDialog.java
  src/gwt/src/org/rstudio/studio/client/projects/model/ProjectTemplateWidget.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/ExistingDirectoryPage.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewDirectoryPage.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/VersionControlPage.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectCompilePdfPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectEditingPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsCustomPanel.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsPanel.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdFileOption.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PublishingPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/SourceControlPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionPreInstallOdbcHost.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileUploadDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobLauncherControls.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/InstallPackageDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewPlumberAPI.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewShinyWebApplication.java
Labels: automation

#5953 Implement version check with --version
  src/cpp/desktop/DesktopMain.cpp
Labels: desktop integration

#5968 bump copyright year in preferences template files
  src/gwt/tools/prefs/UserPrefValues.cpp
  src/gwt/tools/prefs/UserPrefValues.hpp
  src/gwt/tools/prefs/UserPrefsAccessor.java
  src/gwt/tools/prefs/UserStateAccessor.java
  src/gwt/tools/prefs/UserStateValues.cpp
  src/gwt/tools/prefs/UserStateValues.hpp
Labels: developer

#5967 Emit message at end of package installation script
  src/cpp/session/modules/SessionDependencies.cpp
Labels: jobs

#5971 Break out the token specificity in FileType for spellcheck
  src/gwt/src/org/rstudio/studio/client/common/filetypes/CppFileType.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/RFileType.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
  src/gwt/src/org/rstudio/studio/client/common/spelling/domain_specific_words.csv
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSpelling.java
Labels: spellcheck

#5973 Scan R Markdown YAML header for dependencies
  src/cpp/session/modules/SessionCodeTools.R
  src/cpp/tests/testthat/test-pkg-deps.R
Labels: r markdown, yaml

#5976 apply banner, nav, and main landmarks to IDE main window, remove application role
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/include/session/prefs/UserStateValues.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/prefs/UserStateValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/core/client/widget/BannerWidget.java
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/header/MenubarPanel.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
Labels: accessibility

#5983 fix assorted accessibility issues in build output toolbars, connections UI
  src/gwt/src/org/rstudio/core/client/widget/ProgressSpinner.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionCodePanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionExplorer.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/common/CompileOutputPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ChangelistTable.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitChangelistTablePresenter.java
Labels: accessibility

#5981 label nav and main landmarks, give warningbar a role and make its close btn accessible
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
  src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.css
  src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java
  src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.ui.xml
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
Labels: accessibility

#5990 change keyboard shortcuts for next/prev terminal to use Shift instead of Ctrl
  NEWS.md
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Labels: terminal

#5989 include screen reader state in menu text to workaround Qt bug
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
Labels: accessibility

#5996 make min/max/restore quadrant controls fully accessible
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/layout/LogicalWindow.java
  src/gwt/src/org/rstudio/core/client/theme/MinimizedModuleTabLayoutPanel.java
  src/gwt/src/org/rstudio/core/client/theme/MinimizedWindowFrame.java
  src/gwt/src/org/rstudio/core/client/theme/PrimaryWindowFrame.java
  src/gwt/src/org/rstudio/core/client/theme/WindowFrame.java
  src/gwt/src/org/rstudio/core/client/theme/WindowFrameButton.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Labels: accessibility

#6002 Accessibility improvements to editor pane
  src/gwt/src/org/rstudio/core/client/a11y/A11y.java
  src/gwt/src/org/rstudio/core/client/widget/AriaLiveStatusWidget.java
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/application/events/AriaLiveStatusEvent.java
  src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteWindow.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.css
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceShim.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTargetWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTargetWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/ObjectExplorerEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTargetWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTargetWidget.java
Labels: accessibility

#6003 use aria-pressed to make LatchingToolbarButton a toggle button
  src/gwt/src/org/rstudio/core/client/widget/LatchingToolbarButton.java
  src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Labels: accessibility

#6009 support F13 - F24 for custom keyboard shortcuts
  NEWS.md
  src/gwt/src/org/rstudio/core/client/command/KeyboardHelper.java
  src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java
Labels: workbench

#6010 provide alt-text for images in Environment pane
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/CallFramePanel.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.java
Labels: accessibility

#6011 mark tabset quadrants as named regions
  src/gwt/src/org/rstudio/core/client/theme/WindowFrame.java
Labels: accessibility

#6014 announce when Console is cleared via aria-live
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
Labels: accessibility

#6016 stop using aria-modal property on modal dialogs
  src/gwt/src/org/rstudio/core/client/a11y/A11y.java
  src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
Labels: accessibility

#6021 annotate minimized quadrant as a region and as a tabpanel
  src/gwt/src/org/rstudio/core/client/theme/MinimizedModuleTabLayoutPanel.java
  src/gwt/src/org/rstudio/core/client/theme/MinimizedWindowFrame.java
Labels: accessibility

#6022 add shortcut keys to recently added menu items
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Labels: accessibility

#6017 Use R_NoSave over R_Slave for R 4.0+
  src/cpp/r/CMakeLists.txt
  src/cpp/r/config.h.in
  src/cpp/r/session/REmbeddedPosix.cpp
Labels: r interface

#6030 Tolerate invalid user prefs data, with a warning
  src/cpp/desktop/DesktopWebPage.cpp
  src/cpp/session/modules/SessionUserPrefs.cpp
  src/cpp/session/prefs/PrefLayer.cpp
Labels: user preferences

#6033 accessibility labels for images used in Git history UI
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/DiffFrame.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/DiffFrame.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/graph/GraphLine.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/dialog/SVNReviewPanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/dialog/SVNReviewPanel.ui.xml
Labels: accessibility

#6032 Enable the job's progress bar to be clicked to open the job output
  src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.ui.xml
Labels: jobs

#5954 Exclude patterns and files from Find In Files search and replace
  src/cpp/session/modules/SessionFiles.cpp
  src/cpp/session/modules/SessionFind.cpp
  src/cpp/session/modules/SessionFind.hpp
  src/cpp/session/modules/SessionFindTests.cpp
  src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/model/FilesServerOperations.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindInFilesServerOperations.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindInFilesState.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindResult.java
Labels: find in files

#6043 fix layout of ProgressDialog on Safari
  src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.java
Labels: workbench

#6046 prevent JavaScript exception when tabbing through ConsoleProgressDialogs
  src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Labels: accessibility

#6052 enable use of Toggle tri-state checkboxes via keyboard and screen reader
  src/gwt/src/org/rstudio/core/client/widget/Toggle.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/ChunkOptionsPopupPanel.java
Labels: accessibility

#6050 label assorted images missed on previous passes and annotate ProgressDialog
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleError.ui.xml
  src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionPreInstallOdbcHost.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkConditionBar.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkHtmlPreview.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/NotebookProgressWidget.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressWidget.java
Labels: accessibility

#6054 remove document outline from tab sequence when hidden
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Labels: accessibility

#6055 use different keyboard shortcut for Global Options on Safari/Firefox
  src/gwt/src/org/rstudio/core/client/BrowseCap.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Labels: accessibility

#6061 fix reference to 'studio' from 'core' in ProgressDialog abstract class
  src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java
Labels: developer

#6062 Refactor/centralize aria live announcements
  src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java
  src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
  src/gwt/src/org/rstudio/studio/client/application/events/AriaLiveStatusEvent.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
  src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
Labels: accessibility

#6056 Avoid stealing focus when closing tabs
  src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
  src/gwt/src/org/rstudio/core/client/theme/DocTabSelectionEvent.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Labels: debugging

#6064 Fixes some doxygen issues in Logger.hpp
  src/cpp/shared_core/include/shared_core/Logger.hpp
Labels: developer

#6072 assign unique-id to the RStudio Logo anchor
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
Labels: automation

#6071 add user prefs to disable individual aria-live announcements
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/core/client/widget/CheckBoxList.css
  src/gwt/src/org/rstudio/core/client/widget/CheckBoxList.java
  src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
  src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/ShellPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
Labels: accessibility

#6082 add user prefs to control warning bar, info bar, and session state announcements
  src/gwt/src/org/rstudio/core/client/widget/InfoBar.java
  src/gwt/src/org/rstudio/core/client/widget/InfoBar.ui.xml
  src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
  src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java
  src/gwt/src/org/rstudio/studio/client/application/ui/serializationprogress/ApplicationSerializationProgress.java
  src/gwt/src/org/rstudio/studio/client/application/ui/serializationprogress/ApplicationSerializationProgressLabel.java
Labels: accessibility

#6087 emit aria-live alert at startup if screen reader support not enabled (Server only)
  src/gwt/src/org/rstudio/core/client/widget/AriaLiveStatusReporter.java
  src/gwt/src/org/rstudio/core/client/widget/AriaLiveStatusWidget.java
  src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
  src/gwt/src/org/rstudio/core/client/widget/ModalDialogTracker.java
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/application/ApplicationView.java
  src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
  src/gwt/src/org/rstudio/studio/client/application/events/AriaLiveStatusEvent.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
  src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteWindow.java
  src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
Labels: accessibility

#6094 Console output screen-reader announcement implementation
  src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java
  src/gwt/src/org/rstudio/core/client/VirtualConsole.java
  src/gwt/src/org/rstudio/studio/client/common/shell/AriaLiveShellWidget.java
  src/gwt/src/org/rstudio/studio/client/common/shell/ShellDisplay.java
  src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/events/ScreenReaderStateReadyEvent.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/ShellPane.java
  src/gwt/test/org/rstudio/core/client/ConsoleOutputWriterTests.java
  src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Labels: accessibility

#6097 move announcements preferences to separate pref pane tab
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java
Labels: accessibility

#6040 Add Package Source to Find In Files include options
  src/cpp/session/modules/SessionFiles.cpp
  src/cpp/session/modules/SessionFind.cpp
  src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
  src/gwt/src/org/rstudio/core/client/widget/FormListBox.java
  src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/model/FilesServerOperations.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
Labels: find in files

#6102 keyboard and screenreader support for dropdown in slides and help panes
  src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
  src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
  src/gwt/src/org/rstudio/core/client/widget/Toolbar.java
Labels: accessibility

#6107 ensure menu buttons have correct expanded state after menu closes
  src/gwt/src/org/rstudio/core/client/a11y/A11y.java
  src/gwt/src/org/rstudio/core/client/widget/Toolbar.java
  src/gwt/src/org/rstudio/core/client/widget/ToolbarMenuButton.java
Labels: accessibility

#6108 add keyboard shortcuts for next/previous help page, and for searching R Help
  NEWS.md
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/help/Help.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpTab.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/help/search/HelpSearch.java
Labels: accessibility, help pane

#6114 fix resetting of ANSI console color 255 (foreground or background)
  src/gwt/src/org/rstudio/core/client/AnsiCode.java
  src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Labels: console

#6109 Blacklist for Typo.js unsupported dictionaries
  src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/SpellingPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSpelling.java
Labels: spellcheck

#6119 fix broken "build" keyboard shortcut
  src/gwt/src/org/rstudio/core/client/widget/ShortcutInfoPanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/www/docs/keyboard.htm
Labels: accessibility

#6120 Improve screen reader accessibility of "All Keyboard Shortcuts" page
  src/gwt/www/docs/keyboard.htm
Labels: accessibility

#6124 Show accessible keyboard shortcut help when screenreader enabled
  src/gwt/src/org/rstudio/core/client/command/ShortcutViewer.java
  src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
Labels: accessibility

#6126 tweaks to keyboard shortcuts page
  src/gwt/www/docs/keyboard.htm
Labels: accessibility
