Repository rstudio/rstudio, pull requests merged in 2020-08, with the labels that each got.

#7519 fix install-crashpad so it can install pre-built macOS binaries
  dependencies/common/install-crashpad
Labels: developer

#7533 remove duplicate element IDs on sign-in page
  src/gwt/www/templates/encrypted-sign-in.htm
Labels: accessibility

#7537 fix static-initialization order dependency leading to rsession unit test segfault
  src/cpp/shared_core/FilePath.cpp
Labels: automation, developer

#7497 allow customization of default Python interpreter used by reticulate
  src/cpp/r/R/Tools.R
  src/cpp/session/CMakeLists.txt
  src/cpp/session/SessionClientInit.cpp
  src/cpp/session/SessionMain.cpp
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/modules/SessionCodeTools.R
  src/cpp/session/modules/SessionPythonEnvironments.R
  src/cpp/session/modules/SessionPythonEnvironments.cpp
  src/cpp/session/modules/SessionPythonEnvironments.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java
  src/gwt/src/org/rstudio/core/client/prefs/RestartRequirement.java
  src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
  src/gwt/src/org/rstudio/core/client/widget/UserPrefMenuItem.java
  src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
  src/gwt/src/org/rstudio/studio/client/common/icons/code/CodeIcons.java
  src/gwt/src/org/rstudio/studio/client/common/icons/code/conda_2x.png
  src/gwt/src/org/rstudio/studio/client/common/icons/code/python_2x.png
  src/gwt/src/org/rstudio/studio/client/common/icons/code/virtualenv_2x.png
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialog.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/ProjectBuildToolsPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
  src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
  src/gwt/src/org/rstudio/studio/client/workbench/model/WorkbenchServerOperations.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonDialogResources.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonInterpreter.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonInterpreters.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPane.css
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonServerOperations.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/iconPython_2x.png
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterListEntryUi.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterListEntryUi.ui.xml
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterSelectionDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionInstallOdbcPage.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackagesServerOperations.java
Labels: python

#7542 modernize a couple more events into the single-file format
  src/gwt/src/org/rstudio/core/client/widget/FastSelectTable.java
  src/gwt/src/org/rstudio/core/client/widget/events/GlassVisibilityEvent.java
  src/gwt/src/org/rstudio/core/client/widget/events/GlassVisibilityHandler.java
  src/gwt/src/org/rstudio/core/client/widget/events/SelectionChangedEvent.java
  src/gwt/src/org/rstudio/core/client/widget/events/SelectionChangedHandler.java
  src/gwt/src/org/rstudio/studio/client/common/AutoGlassAttacher.java
  src/gwt/src/org/rstudio/studio/client/common/AutoGlassPanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerDataGrid.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerEditingTargetStatusBar.java
Labels: developer

#7547 improve DialogTabLayoutPanel to manage focus loop automatically
  src/gwt/src/org/rstudio/core/client/theme/DialogTabLayoutPanel.java
  src/gwt/src/org/rstudio/core/client/widget/FocusHelper.java
  src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditCodeBlockDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditImageDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditLinkDialog.java
Labels: accessibility

#7558 Fix issues with Console handling of inverted color mode
  src/gwt/src/org/rstudio/core/client/AnsiCode.java
  src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Labels: console

#7565 add script for minifying the data viewer JS
  src/cpp/session/resources/grid/minify.sh
Labels: developer

#7570 suppress focus outlines for console output regions
  src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleResources.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/consoleStyles.css
Labels: accessibility

#7571 mechanical cleanup of code I'm about to touch
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBar.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarElement.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarElementWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarPopupMenu.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarPopupRequest.java
Labels: developer

#7578 fix keyboard operation of unfocused ToolbarPopupMenus
  src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserContextWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionPopupMenu.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarPopupMenu.java
Labels: accessibility

#7595 Install NSIS from S3
  docker/jenkins/Dockerfile.windows
Labels: builds

#7601 reduce font-size differences between Console and Terminal
  NEWS.md
  src/gwt/src/org/rstudio/core/client/widget/FontSizer.css
  src/gwt/src/org/rstudio/core/client/widget/FontSizer.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermOptions.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermTheme.java
Labels: terminal

#7605 Always show focus rectangle after using Focus Main Toolbar command
  src/gwt/src/org/rstudio/core/client/a11y/A11y.java
  src/gwt/src/org/rstudio/studio/client/application/ui/GlobalToolbar.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchPane.java
Labels: accessibility

#7596 Scroll to a specified position in an unknown file
  src/cpp/r/R/Api.R
  src/cpp/session/modules/environment/SessionEnvironment.cpp
  src/gwt/src/org/rstudio/studio/client/common/filetypes/events/OpenSourceFileEvent.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/events/JumpToFunctionEvent.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/NavigableSourceEditor.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/ScrollToPositionEvent.java
Labels: rstudioapi

#7612 Prevent terminal from becoming unresponsive after console panel tabs added or removed
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
Labels: terminal

#7642 change some string comparisons to use StringUtil.equals
  src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneConfig.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
Labels: developer

#7647 Fix regression where opening a source file wouldn't move the cursor
  src/gwt/src/org/rstudio/studio/client/common/filetypes/events/OpenSourceFileEvent.java
Labels: source navigation

#7646 Update xterm.js to 4.8.1 to obtain fix for error logged in browser console
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/xterm.css
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/xterm.js
  src/gwt/tools/build-xterm
Labels: terminal

#7655 Persist minimized state for main source pane
  src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Labels: source editor

#7627 guard against missing bin directory in tinytex install
  src/cpp/session/modules/SessionRMarkdown.R
Labels: r markdown

#7641 be more careful when cleaning up file monitor contexts
  src/cpp/core/system/file_monitor/Win32FileMonitor.cpp
Labels: windows

#7659 Reduce number of cores used for official build
  Jenkinsfile
Labels: builds

#7671 cherry-pick file-monitor crash fix from master
  NEWS-1.3.md
  src/cpp/core/system/file_monitor/Win32FileMonitor.cpp
Labels: files pane, regression

#7689 don't log monitor interrupt errors
  src/cpp/core/system/PosixFileScanner.cpp
  src/cpp/core/system/System.cpp
  src/cpp/r/session/RStdCallbacks.cpp
  src/cpp/session/SessionMain.cpp
  src/cpp/shared_core/Error.cpp
  src/cpp/shared_core/Logger.cpp
  src/cpp/shared_core/include/shared_core/Error.hpp
Labels: logging

#7656 allow for project-specific Python options
  src/cpp/core/include/core/r_util/RProjectFile.hpp
  src/cpp/core/r_util/RProjectFile.cpp
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/modules/SessionPythonEnvironments.R
  src/cpp/session/modules/SessionPythonEnvironments.cpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/projects/SessionProjectContext.cpp
  src/cpp/session/projects/SessionProjects.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java
  src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogPaneBase.java
  src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
  src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
  src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java
  src/gwt/src/org/rstudio/studio/client/projects/model/RProjectConfig.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialog.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPythonPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/Prefs.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPane.css
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPaneBase.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonServerOperations.java
Labels: python

#7606 index R6 class method definitions; add to fuzzy finder
  NEWS.md
  src/cpp/core/r_util/RSourceIndex.cpp
  src/cpp/session/modules/SessionCodeSearch.cpp
Labels: fuzzy finder
