Repository rstudio/rstudio, pull requests merged in 2021-04, with the labels that each got.

#9197 support running dev desktop build (qt) with cmake generation from repo root
  src/cpp/desktop/DesktopMain.cpp
Labels: developer

#9224 launch rsession-arm64 via /usr/bin/arch -arm64
  src/cpp/desktop/DesktopSessionLauncher.cpp
Labels: macos

#9248 install R 3.6.3 (up from 3.5) via PowerShell bootstrapper
  dependencies/windows/Install-RStudio-Prereqs.ps1
Labels: developer

#9259 update xterm.js to ver 4.11.0
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/fit.js
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/xterm.js
  src/gwt/tools/build-xterm
Labels: terminal

#9263 clean-rstudio script missing some folders
  scripts/clean-rstudio
Labels: developer

#9283 support R graphics engine 14
  NEWS.md
  src/cpp/core/include/core/FileInfo.hpp
  src/cpp/core/system/file_monitor/FileMonitor.cpp
  src/cpp/r/session/graphics/RGraphicsDevDesc.cpp
  src/cpp/r/session/graphics/RGraphicsDevDesc.hpp
  src/cpp/r/session/graphics/RGraphicsDevDescVersions.hpp
  src/cpp/r/session/graphics/RGraphicsDevice.cpp
  src/cpp/r/session/graphics/RGraphicsDevice.hpp
  src/cpp/r/session/graphics/RGraphicsHandler.cpp
  src/cpp/r/session/graphics/RGraphicsHandler.hpp
  src/cpp/r/session/graphics/RGraphicsUtils.cpp
  src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp
  src/cpp/session/modules/SessionGraphics.cpp
  src/tools/gcc-ubsan-build
Labels: plots
