Repository rstudio/rstudio, pull requests merged in 2021-08, with the labels that each got.

#9689 WIP on package-helper script for building Win32 package
  src/node/desktop/package.json
  src/node/desktop/scripts/package-helper.ts
  src/node/desktop/scripts/script-tools.ts
  src/node/desktop/yarn.lock
Labels: electron

#9711 Fix packaged Windows layout (Electron)
  src/node/desktop/scripts/package-helper.ts
Labels: electron

#9696 Feature/gwt callbacks craig
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/renderer/desktop-bridge.ts
  src/node/desktop/test/unit/core/file-path.test.ts
Labels: electron

#9717 implement MainWindow.closeEvent (Electron)
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/session-servers-overlay.ts
  src/node/desktop/test/int/session-restart.test.ts
Labels: electron

#9725 Don't reload "loading" page while waiting for session (Electron)
  src/node/desktop/src/main/main-window.ts
Labels: electron

#9733 Support launching _blank URLs and help links in browser (Electron)
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/gwt-window.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/pending-window.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/src/main/web-view.ts
  src/node/desktop/src/main/window-utils.ts
  src/node/desktop/test/unit/main/pending-window.test.ts
  src/node/desktop/test/unit/main/web-view.test.ts
Labels: electron

#9735 enable external links in secondary windows
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/main-window.ts
Labels: electron

#9737 Enable satellite windows in Electron desktop
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-window.ts
  src/node/desktop/src/main/satellite-window.ts
  src/node/desktop/src/main/secondary-window.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/src/main/window-utils.ts
  src/node/desktop/test/unit/main/utils.test.ts
Labels: electron

#9682 implement Choose R dialog for Windows
  src/node/desktop/.eslintrc.js
  src/node/desktop/package.json
  src/node/desktop/scripts/copy-files.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/detect-r.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/ui/README.md
  src/node/desktop/src/ui/modal-dialog.ts
  src/node/desktop/src/ui/widgets/choose-r.ts
  src/node/desktop/src/ui/widgets/choose-r/load.ts
  src/node/desktop/src/ui/widgets/choose-r/preload.ts
  src/node/desktop/src/ui/widgets/choose-r/styles.css
  src/node/desktop/src/ui/widgets/choose-r/ui.html
  src/node/desktop/tsconfig.json
Labels: windows, electron

#9740 misc features for secondary and satellite windows
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/satellite-window.ts
  src/node/desktop/src/main/secondary-window.ts
  src/node/desktop/src/main/window-utils.ts
Labels: electron

#9742 implement callbacks for cursor hit detection (Electron)
  src/node/desktop/src/main/gwt-callback.ts
Labels: electron

#9746 Update dependencies: electron 13.2, playwright 1.14.0
  src/node/desktop/yarn.lock
Labels: electron

#9749 Set LANG/LC_CTYPE for Mac desktop (Electron)
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/utils.ts
Labels: electron

#9750 Electron: pass through activation click and implement activation callbacks
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/src/main/window-utils.ts
Labels: electron

#9751 implement default context menu for Electron
  src/node/desktop/src/main/context-menu.ts
  src/node/desktop/src/main/desktop-browser-window.ts
Labels: electron

#9747 use web dialogs for input prompts w/Electron
  src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
  src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/renderer/desktop-bridge.ts
Labels: electron

#9770 Integrate electron-forge and webpack (Electron)
  src/node/desktop/.eslintignore
  src/node/desktop/.gitignore
  src/node/desktop/package.json
  src/node/desktop/scripts/copy-files.ts
  src/node/desktop/scripts/mac-package
  src/node/desktop/scripts/script-tools.ts
  src/node/desktop/src/core/template-filter.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/main/product-info.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/renderer/desktop-bridge.ts
  src/node/desktop/src/renderer/renderer.ts
  src/node/desktop/src/ui/connect/connect.html
  src/node/desktop/src/ui/connect/connect.ts
  src/node/desktop/src/ui/error/error.html
  src/node/desktop/src/ui/error/error.ts
  src/node/desktop/src/ui/loading/loading.html
  src/node/desktop/src/ui/loading/loading.ts
  src/node/desktop/src/ui/modal-dialog.ts
  src/node/desktop/src/ui/widgets/choose-r.ts
  src/node/desktop/src/ui/widgets/choose-r/load.ts
  src/node/desktop/src/ui/widgets/choose-r/ui.html
  src/node/desktop/test/int/int-utils.ts
  src/node/desktop/test/int/startup-fail-session.test.ts
  src/node/desktop/test/unit/core/template-filter.test.ts
  src/node/desktop/webpack.main.config.js
  src/node/desktop/webpack.plugins.js
  src/node/desktop/webpack.renderer.config.js
  src/node/desktop/webpack.rules.js
  src/node/desktop/yarn.lock
Labels: developer, electron

#9793 update Electron-Forge to latest
  src/node/desktop/.eslintrc.js
  src/node/desktop/package.json
  src/node/desktop/src/core/console-logger.ts
  src/node/desktop/src/core/err.ts
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/src/core/file-serializer.ts
  src/node/desktop/src/core/logger.ts
  src/node/desktop/src/core/system.ts
  src/node/desktop/src/core/user.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/detect-r.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/ui/modal-dialog.ts
  src/node/desktop/test/unit/core/err.test.ts
  src/node/desktop/test/unit/core/file-path.test.ts
  src/node/desktop/tsconfig.json
  src/node/desktop/webpack.rules.js
  src/node/desktop/yarn.lock
Labels: developer, electron

#9794 move forge config into separate JS file (Electron)
  src/node/desktop/.eslintignore
  src/node/desktop/forge.config.js
  src/node/desktop/package.json
Labels: developer
