Repository rstudio/rstudio, pull requests merged in 2021-09, with the labels that each got.

#9871 additional work on fold commands for visual mode
  src/gwt/panmirror/src/editor/src/api/command.ts
  src/gwt/panmirror/src/editor/src/api/ui.ts
  src/gwt/panmirror/src/editor/src/behaviors/outline.ts
  src/gwt/panmirror/src/editor/src/behaviors/spelling/spelling-realtime.ts
  src/gwt/panmirror/src/editor/src/editor/editor-extensions.ts
  src/gwt/panmirror/src/editor/src/editor/editor-theme.ts
  src/gwt/panmirror/src/editor/src/optional/ace/ace-node-views.ts
  src/gwt/panmirror/src/editor/src/optional/ace/ace.css
  src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
  src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorCommandUI.java
  src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorCommands.java
  src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorToolbarCommands.java
  src/gwt/src/org/rstudio/studio/client/panmirror/ui/PanmirrorUIChunkEditor.java
  src/gwt/src/org/rstudio/studio/client/panmirror/ui/PanmirrorUIChunks.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextUi.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.css
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunks.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/ui/CollapseToggle.css
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/ui/VisualModeCollapseToggle.java
Labels: visual markdown editing

#9885 run GWT (Java) build step after C++ builds complete
  src/gwt/CMakeLists.txt
Labels: builds, developer

#9889 use all cores on Mac builder
  package/osx/make-package
Labels: builds, developer

#9888 Fix race condition in notebook autosave
  NEWS.md
  src/cpp/session/modules/rmarkdown/NotebookCache.cpp
  src/cpp/session/modules/rmarkdown/NotebookCache.hpp
  src/cpp/session/modules/rmarkdown/NotebookExec.cpp
  src/cpp/session/modules/rmarkdown/NotebookExec.hpp
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/DocUpdateSentinel.java
Labels: notebooks, autosave

#9766 use double indent for function parameters
  NEWS.md
  src/gwt/acesupport/acemode/auto_brace_insert.js
  src/gwt/acesupport/acemode/r_code_model.js
  src/gwt/acesupport/acemode/r_matching_brace_outdent.js
  src/gwt/acesupport/acemode/rmarkdown.js
  src/gwt/test/autoindent_test_r.html
Labels: ace
