Repository rstudio/rstudio, pull requests merged in 2021-11, with the labels that each got.

#9987 Add i18n for menu headings and commands
  src/gwt/build.xml
  src/gwt/src/org/rstudio/core/rebind/command/CommandBundleGenerator.java
  src/gwt/src/org/rstudio/core/rebind/command/MenuEmitter.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/.gitattributes
  src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml.MD5
  src/gwt/src/org/rstudio/studio/client/workbench/commands/MenuConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/commands/MenuConstants_en.properties
  src/gwt/tools/i18n-helpers/README.md
  src/gwt/tools/i18n-helpers/commands.cmd.xml/.gitignore
  src/gwt/tools/i18n-helpers/commands.cmd.xml/commands_xml_to_i18n.py
  src/gwt/tools/i18n-helpers/commands.cmd.xml/element_parsers.py
  src/gwt/tools/i18n-helpers/commands.cmd.xml/i18n_gwt_interface.py
  src/gwt/tools/i18n-helpers/commands.cmd.xml/requirements.txt
  src/gwt/tools/i18n-helpers/commands.cmd.xml/sample_commands.cmd.xml
  src/gwt/tools/i18n-helpers/commands.cmd.xml/test_commands_xml_to_i18n.py
  src/gwt/tools/i18n-helpers/commands.cmd.xml/xml_to_i18n.py
  src/gwt/tools/i18n-helpers/python-check-version.py
Labels: developer, locale

#10057 Update Electron project packages
  src/node/desktop/package.json
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/tsconfig.json
  src/node/desktop/yarn.lock
Labels: electron

#10080 Automate dependencies for i18n regeneration
  .devcontainer/Dockerfile
  dependencies/linux/install-dependencies-bionic
  dependencies/linux/install-dependencies-focal
  dependencies/linux/install-dependencies-stretch
  dependencies/osx/install-dependencies-osx
  dependencies/osx/install-dependencies-osx-arch
  dependencies/windows/Install-RStudio-Prereqs.ps1
  dependencies/windows/install-dependencies.cmd
  dependencies/windows/tools/.gitignore
  src/gwt/ant
  src/gwt/build.xml
  src/gwt/tools/i18n-helpers/.gitignore
  src/gwt/tools/i18n-helpers/commands.cmd.xml/.gitignore
  src/gwt/tools/i18n-helpers/python-check-version.py
Labels: developer

#10098 Use native M1 Java if available when building on M1 Mac
  dependencies/tools/rstudio-tools.sh
  package/osx/make-package
  src/gwt/ant
Labels: developer

#10104 Package JSON and Yarn Lock files were updated for consistency.
  src/node/desktop/package.json
  src/node/desktop/yarn.lock
Labels: electron

#10117 generate rdesktop-dev.conf on M1 mac for dev builds
  src/cpp/CMakeLists.txt
Labels: electron

#10120 fix mac dependency scripts to create /opt/rstudio-tools via sudo if necessary
  dependencies/osx/install-dependencies-osx
  dependencies/tools/rstudio-tools.sh
Labels: developer

#10099 Rohan i18nify studio client application
  src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
  src/gwt/src/org/rstudio/studio/client/application/Application.java
  src/gwt/src/org/rstudio/studio/client/application/ApplicationInterrupt.java
  src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
  src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
  src/gwt/src/org/rstudio/studio/client/application/DesktopHooks.java
  src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants.java
  src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/application/model/HttpLogEntry.java
  src/gwt/src/org/rstudio/studio/client/application/model/ProductEditionInfo.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialog.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogConstants.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogMessages.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogMessages_en.properties
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutOpenSourceDialog.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
  src/gwt/src/org/rstudio/studio/client/application/ui/GlobalToolbar.java
  src/gwt/src/org/rstudio/studio/client/application/ui/ProjectPopupMenu.java
  src/gwt/src/org/rstudio/studio/client/application/ui/RVersionSelectWidget.java
  src/gwt/src/org/rstudio/studio/client/application/ui/RequestLogDetail.java
  src/gwt/src/org/rstudio/studio/client/application/ui/RequestLogVisualization.java
  src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java
  src/gwt/src/org/rstudio/studio/client/application/ui/addins/AddinsToolbarButton.java
  src/gwt/src/org/rstudio/studio/client/application/ui/appended/ApplicationEndedPopupPanel.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
Labels: locale

#10090 Rohan i18nify org rstudio core
  src/gwt/src/org/rstudio/core/client/CoreClientConstants.java
  src/gwt/src/org/rstudio/core/client/CoreClient_en.properties
  src/gwt/src/org/rstudio/core/client/MessageDisplay.java
  src/gwt/src/org/rstudio/core/client/StringUtil.java
  src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java
  src/gwt/src/org/rstudio/core/client/command/ShortcutViewer.java
  src/gwt/src/org/rstudio/core/client/files/PosixFileSystemContext.java
  src/gwt/src/org/rstudio/core/client/files/filedialog/ChooseFolderDialog2.java
  src/gwt/src/org/rstudio/core/client/files/filedialog/DirectoryContentsWidget.java
  src/gwt/src/org/rstudio/core/client/files/filedialog/FileDialog.java
  src/gwt/src/org/rstudio/core/client/files/filedialog/FileSystemDialog.java
  src/gwt/src/org/rstudio/core/client/files/filedialog/OpenProjectDialog.java
  src/gwt/src/org/rstudio/core/client/files/filedialog/PathBreadcrumbWidget.java
  src/gwt/src/org/rstudio/core/client/files/filedialog/SaveFileDialog.java
  src/gwt/src/org/rstudio/core/client/jsonrpc/RpcRequest.java
  src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java
  src/gwt/src/org/rstudio/core/client/promise/PromiseWithProgress.java
  src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
  src/gwt/src/org/rstudio/core/client/theme/MinimizedModuleTabLayoutPanel.java
  src/gwt/src/org/rstudio/core/client/theme/MinimizedWindowFrame.java
  src/gwt/src/org/rstudio/core/client/theme/ModuleTabLayoutPanel.java
  src/gwt/src/org/rstudio/core/client/theme/WindowFrameButton.java
  src/gwt/src/org/rstudio/core/client/widget/DocPropMenuItem.java
  src/gwt/src/org/rstudio/core/client/widget/FullscreenPopupPanel.java
  src/gwt/src/org/rstudio/core/client/widget/HtmlFormModalDialog.java
  src/gwt/src/org/rstudio/core/client/widget/InfoBar.java
  src/gwt/src/org/rstudio/core/client/widget/LocalRepositoriesWidget.java
  src/gwt/src/org/rstudio/core/client/widget/MiniDialogPopupPanel.java
  src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
  src/gwt/src/org/rstudio/core/client/widget/ModifyKeyboardShortcutsWidget.java
  src/gwt/src/org/rstudio/core/client/widget/MonitoringMenuItem.java
  src/gwt/src/org/rstudio/core/client/widget/NullProgressIndicator.java
  src/gwt/src/org/rstudio/core/client/widget/NumericValueWidget.java
  src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.java
  src/gwt/src/org/rstudio/core/client/widget/ProgressSpinner.java
  src/gwt/src/org/rstudio/core/client/widget/SatelliteFramePanel.java
  src/gwt/src/org/rstudio/core/client/widget/SearchWidget.java
  src/gwt/src/org/rstudio/core/client/widget/SelectWidget.java
  src/gwt/src/org/rstudio/core/client/widget/ShortcutInfoPanel.java
  src/gwt/src/org/rstudio/core/client/widget/ShowContentDialog.java
  src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
  src/gwt/src/org/rstudio/core/client/widget/TextEntryModalDialog.java
  src/gwt/src/org/rstudio/core/client/widget/VimKeyInfoPanel.java
  src/gwt/src/org/rstudio/core/client/widget/Wizard.java
  src/gwt/src/org/rstudio/core/client/widget/images/MessageDialogImages.java
Labels: locale

#10095 i18nify org.rstudio.studio.client.common
  src/gwt/src/org/rstudio/studio/client/common/DefaultGlobalDisplay.java
  src/gwt/src/org/rstudio/studio/client/common/GlobalProgressDelayer.java
  src/gwt/src/org/rstudio/studio/client/common/SimpleRequestCallback.java
  src/gwt/src/org/rstudio/studio/client/common/StudioClientCommonConstants.java
  src/gwt/src/org/rstudio/studio/client/common/StudioClientCommonConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/common/compile/CompilePanel.java
  src/gwt/src/org/rstudio/studio/client/common/debugging/BreakpointManager.java
  src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleError.java
  src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleErrorFrame.java
  src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
  src/gwt/src/org/rstudio/studio/client/common/dialog/DesktopDialogBuilderFactory.java
  src/gwt/src/org/rstudio/studio/client/common/fileexport/FileExport.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/CodeBrowserType.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/DataFrameType.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/FileIcon.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/ObjectExplorerFileType.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/ProfilerType.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/RPresentationFileType.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/StanFileType.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
  src/gwt/src/org/rstudio/studio/client/common/filetypes/UrlContentType.java
  src/gwt/src/org/rstudio/studio/client/common/impl/DesktopFileDialogs.java
  src/gwt/src/org/rstudio/studio/client/common/impl/DesktopTextInput.java
  src/gwt/src/org/rstudio/studio/client/common/impl/WebFileDialogs.java
  src/gwt/src/org/rstudio/studio/client/common/latex/LatexProgramRegistry.java
  src/gwt/src/org/rstudio/studio/client/common/latex/LatexProgramSelectWidget.java
  src/gwt/src/org/rstudio/studio/client/common/mirrors/DefaultCRANMirror.java
  src/gwt/src/org/rstudio/studio/client/common/r/roxygen/RoxygenHelper.java
  src/gwt/src/org/rstudio/studio/client/common/rnw/RnwWeaveRegistry.java
  src/gwt/src/org/rstudio/studio/client/common/rnw/RnwWeaveSelectWidget.java
  src/gwt/src/org/rstudio/studio/client/common/rpubs/RPubsUploader.java
  src/gwt/src/org/rstudio/studio/client/common/rpubs/ui/RPubsUploadDialog.java
  src/gwt/src/org/rstudio/studio/client/common/rstudioapi/RStudioAPI.java
  src/gwt/src/org/rstudio/studio/client/common/rstudioapi/ui/AskSecretDialog.java
  src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteManager.java
  src/gwt/src/org/rstudio/studio/client/common/shell/AriaLiveShellWidget.java
  src/gwt/src/org/rstudio/studio/client/common/shell/ShellInteractionManager.java
  src/gwt/src/org/rstudio/studio/client/common/sourcemarkers/SourceMarkerItemCodec.java
  src/gwt/src/org/rstudio/studio/client/common/sourcemarkers/SourceMarkerList.java
  src/gwt/src/org/rstudio/studio/client/common/synctex/Synctex.java
  src/gwt/src/org/rstudio/studio/client/common/vcs/AskPassManager.java
  src/gwt/src/org/rstudio/studio/client/common/vcs/ShowPublicKeyDialog.java
  src/gwt/src/org/rstudio/studio/client/common/vcs/SshKeyWidget.java
  src/gwt/src/org/rstudio/studio/client/common/vcs/ignore/Ignore.java
  src/gwt/src/org/rstudio/studio/client/common/vcs/ignore/IgnoreDialog.java
  src/gwt/src/org/rstudio/studio/client/common/viewfile/ViewFilePanel.java
Labels: locale

#10136 Fixed issue with Electron showErrorBox function
  src/node/desktop/NEWS-electron.md
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/context-menu.ts
  src/node/desktop/src/main/detect-r.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/main/utils.ts
Labels: developer, electron

#10135 i18nify client panmirror
  src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorConstants.java
  src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorCommandPaletteEntry.java
  src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorCommandPaletteItem.java
  src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorToolbar.java
  src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorToolbarCommands.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorDialogs.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditCalloutDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditCodeBlockDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditImageDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditLinkDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditListDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditMathDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditRawDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorHRefSelect.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorHTMLDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorImageChooser.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorInsertCiteDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorInsertTableDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorInsertTabsetDialog.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorRawFormatSelect.java
  src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/model/PanmirrorListIncremental.java
  src/gwt/src/org/rstudio/studio/client/panmirror/findreplace/PanmirrorFindReplaceWidget.java
  src/gwt/src/org/rstudio/studio/client/panmirror/outline/PanmirrorOutlineWidget.java
  src/gwt/src/org/rstudio/studio/client/panmirror/pandoc/PanmirrorPandocServer.java
  src/gwt/src/org/rstudio/studio/client/panmirror/server/PanmirrorDOIServer.java
  src/gwt/src/org/rstudio/studio/client/panmirror/server/PanmirrorZoteroServer.java
Labels: locale

#10137 i18n for source.editors.text
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkConsolePage.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkHtmlPage.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputGallery.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkSatelliteWindow.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ImagePreviewPopup.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ImagePreviewer.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCompilePdfHelper.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCppHelper.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetFindReplace.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetJSHelper.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetLatexFormatMenu.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetPresentationHelper.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetRMarkdownHelper.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSpelling.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSqlHelper.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Labels: locale

#10158 Build packages with Ninja on Linux
  docker/jenkins/Dockerfile.bionic-amd64
  docker/jenkins/Dockerfile.centos7-x86_64
  docker/jenkins/Dockerfile.centos8-x86_64
  docker/jenkins/Dockerfile.debian9-x86_64
  docker/jenkins/Dockerfile.opensuse15-x86_64
  package/linux/make-package
Labels: builds

#10165 Reduce duplicate file from error to warning for ninja
  package/linux/make-package
Labels: builds
