Repository rstudio/rstudio, pull requests merged in 2021-07, with the labels that each got.

#9552 make GwtCallback a singleton (Electron)
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/satellite-window.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/renderer/desktop-bridge.ts
  src/node/desktop/test/unit/main/app-state.test.ts
  src/node/desktop/test/unit/main/minimal-window.test.ts
  src/node/desktop/test/unit/main/satellite-window.test.ts
  src/node/desktop/test/unit/main/session-launcher.test.ts
Labels: developer, electron

#9553 put back toolbar flag, more base window implementation
  src/node/desktop/docs/ElectronWindowClasses.puml
  src/node/desktop/docs/QtWebEngineInstance.puml
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/gwt-window.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/main/minimal-window.ts
  src/node/desktop/src/main/satellite-window.ts
  src/node/desktop/src/main/secondary-window.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/test/unit/core/logger.test.ts
  src/node/desktop/test/unit/main/desktop-browser-window.test.ts
  src/node/desktop/test/unit/main/gwt-window.test.ts
  src/node/desktop/test/unit/main/secondary-window.test.ts
  src/node/desktop/test/unit/main/window-tracker.test.ts
Labels: developer, electron

#9554 use RSTUDIO_WHICH_R to find R on windows (dev mode hack)
  src/node/desktop/package.json
  src/node/desktop/src/main/detect_r.ts
  src/node/desktop/test/unit/main/session-launcher.test.ts
  src/node/desktop/yarn.lock
Labels: developer, electron

#9557 set logging level with command-line, other misc porting
  src/node/desktop/NEWS-electron.md
  src/node/desktop/src/core/logger.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/test/unit/core/logger.test.ts
  src/node/desktop/test/unit/main/window-tracker.test.ts
Labels: developer, electron

#9558 close minimal windows with keyboard and when parent closes
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/minimal-window.ts
  src/node/desktop/test/unit/main/minimal-window.test.ts
Labels: developer, electron

#9560 implement GwtWindow zooming (electron)
  src/node/desktop/src/core/array-utils.ts
  src/node/desktop/src/main/activation-overlay.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/gwt-window.ts
  src/node/desktop/src/main/minimal-window.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/main/web-view.ts
  src/node/desktop/test/unit/core/array-utils.test.ts
  src/node/desktop/test/unit/main/web-view.test.ts
Labels: developer, electron

#9565 gwtcallback emits event when workbench initialized
  src/node/desktop/src/core/err.ts
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/test/unit/core/err.test.ts
  src/node/desktop/test/unit/core/file-path.test.ts
  src/node/desktop/test/unit/main/application.test.ts
Labels: developer, electron

#9572 port the session-launcher launchProcess method
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/test/unit/main/application.test.ts
  src/node/desktop/test/unit/main/utils.test.ts
Labels: developer, electron

#9574 handle escapes in quoted symbols
  src/cpp/core/include/core/r_util/RTokenizer.hpp
  src/cpp/core/r_util/RTokenizer.cpp
  src/cpp/core/r_util/RTokenizerTests.cpp
  src/gwt/acesupport/acemode/r_highlight_rules.js
Labels: r interface

#9585 proof-of-concept Electron integration test with Playwright
  src/node/desktop/package.json
  src/node/desktop/test/int/mocharc.json
  src/node/desktop/test/int/startup.test.ts
  src/node/desktop/yarn.lock
Labels: automation, electron

#9587 remove Electron prototype
  src/node/prototype/.gitignore
  src/node/prototype/README.md
  src/node/prototype/package.json
  src/node/prototype/src/main/app.ts
  src/node/prototype/src/main/desktop-callback.ts
  src/node/prototype/src/main/desktop-info.ts
  src/node/prototype/src/main/main-window.ts
  src/node/prototype/src/main/main.ts
  src/node/prototype/src/main/menu-callback.ts
  src/node/prototype/src/main/pending-window.ts
  src/node/prototype/src/main/r-command-evaluator.ts
  src/node/prototype/src/main/r.ts
  src/node/prototype/src/main/session-launcher.ts
  src/node/prototype/src/renderer/desktop-bridge.ts
  src/node/prototype/src/renderer/desktop-info-bridge.ts
  src/node/prototype/src/renderer/menu-bridge.ts
  src/node/prototype/src/renderer/preload.ts
  src/node/prototype/tsconfig.json
  src/node/prototype/yarn.lock
Labels: developer, electron

#9591 catch exception thrown during startup from Finder
  src/node/desktop/scripts/mac-package
  src/node/desktop/src/main/detect_r.ts
  src/node/desktop/src/main/main.ts
Labels: developer, electron

#9596 support running integration test against packaged build
  src/node/desktop/scripts/update-yarn
  src/node/desktop/test/int/int-utils.ts
  src/node/desktop/test/int/startup.test.ts
Labels: automation, electron

#9592 don't update R variables in Environment pane when Python active
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
Labels: python

#9588 improve handling of errors in render output
  NEWS.md
  src/cpp/session/include/session/SessionModuleContext.hpp
  src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
  src/gwt/src/org/rstudio/studio/client/common/sourcemarkers/SourceMarkerItemCodec.java
  src/gwt/src/org/rstudio/studio/client/common/sourcemarkers/SourceMarkerList.css
Labels: r markdown

#9617 Save main window geometry in same location as in the C++ code
  src/node/desktop/src/main/main-window.ts
Labels: electron

#9630 Add early init of env vars (before logging)
  src/cpp/server/ServerEnvVars.cpp
  src/cpp/server/ServerEnvVars.hpp
  src/cpp/server/ServerMain.cpp
Labels: logging

#9638 Port "Error Starting R" page to Electron
  src/cpp/session/SessionMain.cpp
  src/node/desktop/NOTICE.electron
  src/node/desktop/package.json
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/src/core/file-serializer.ts
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/test/int/int-utils.ts
  src/node/desktop/test/int/startup.test.ts
  src/node/desktop/test/unit/core/file-path.test.ts
  src/node/desktop/test/unit/core/file-serializer.test.ts
  src/node/desktop/yarn.lock
Labels: electron

#9626 wrapping up IDE python integration items
  src/cpp/session/modules/SessionPythonEnvironments.R
  src/cpp/session/resources/terminal/hooks
  src/gwt/acesupport/acemode/r.js
  src/gwt/acesupport/acemode/r_highlight_rules.js
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Labels: python

#9645 Feature/electron window position restore
  src/node/desktop/src/main/desktop-options.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/test/unit/main/desktop-options.test.ts
Labels: electron

#9646 basic integration test for main menu (Electron)
  src/node/desktop/src/main/menu-callback.ts
  src/node/desktop/test/int/mocharc.json
  src/node/desktop/test/int/startup-fail-session.test.ts
  src/node/desktop/test/int/startup.test.ts
Labels: electron

#9651 eliminate "as any" and "eslint-disables" in restore window position unit tests
  src/node/desktop/test/unit/main/desktop-options.test.ts
  src/node/desktop/test/unit/unit-utils.ts
Labels: electron

#9644 support auto-discovery of R on Windows
  src/node/desktop/src/core/expected.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/detect-r.ts
  src/node/desktop/src/main/detect_r.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/test/unit/main/detect-r.test.ts
Labels: electron

#9653 rename FilePath.exists to FilePath.existsAsync (Electron)
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/test/unit/core/file-path.test.ts
  src/node/desktop/test/unit/main/application.test.ts
  src/node/desktop/tsconfig.json
Labels: electron

#9656 use Expected return type in file-path
  src/node/desktop/src/core/file-path.ts
Labels: electron

#9658 use Err instead of Expected for prepareEnvironment
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/detect-r.ts
  src/node/desktop/test/unit/core/expected.test.ts
Labels: electron

#9660 implement "yarn clean" command
  src/node/desktop/.eslintignore
  src/node/desktop/package.json
  src/node/desktop/scripts/clean.ts
  src/node/desktop/scripts/script-tools.ts
  src/node/desktop/tsconfig.json
Labels: developer, electron

#9662 get RStudio running on Linux with Electron
  src/node/desktop/src/main/detect-r.ts
  src/node/desktop/src/main/main.ts
Labels: electron

#9663 fix integration test in dev build
  src/node/desktop/src/main/application.ts
  src/node/desktop/tsconfig.json
Labels: electron

#9664 properly handle UNC paths with git on Windows
  NEWS.md
  src/cpp/session/modules/SessionGit.cpp
Labels: vcs, windows

#9665 simple test for showing secondary window (chome gpu diagnostics) in Electron
  src/node/desktop/src/main/detect-r.ts
  src/node/desktop/test/int/int-utils.ts
  src/node/desktop/test/int/utility-window.test.ts
Labels: electron

#9669 exported functions shouldn't throw (Electron)
  src/node/desktop/src/core/file-serializer.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/test/int/mocharc.json
  src/node/desktop/test/unit/core/file-serializer.test.ts
  src/node/desktop/test/unit/mocharc.json
Labels: electron

#9671 mechanical rename of Success() to success()
  src/node/desktop/src/core/err.ts
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/src/main/detect-r.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/test/unit/core/err.test.ts
Labels: electron

#9670 ensure we use a pre element when computing console width
  NEWS.md
  src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
Labels: console

#9676 implement isMacOS and isCentOS desktop callbacks (Electron)
  src/node/desktop/src/core/system.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/test/unit/core/system.test.ts
Labels: electron

#9681 Backspacing in terminal gets out of sync
  NEWS.md
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermAddon.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermBuffer.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermBufferCell.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermBufferLine.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermBufferNamespace.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermDimensions.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermDisposable.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermFitAddon.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermLinkProvider.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermLocalizableStrings.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermMarker.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermNative.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermOptions.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermParser.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermSelectionPosition.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermTerminal.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermTheme.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermUnicodeHandling.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWebLinksAddon.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWindowOptions.java
Labels: terminal

#9685 complete implementation of get_open_file_name callback
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/test/unit/main/utils.test.ts
Labels: electron
