Repository rstudio/rstudio, pull requests merged in 2021-12, with the labels that each got.

#10167 Implement versioning for Electron Mac package builds
  package/osx/make-package
  src/node/desktop/NEWS-electron.md
  src/node/desktop/README.md
  src/node/desktop/package.json
  src/node/desktop/scripts/update-json-version.sh
  src/node/desktop/yarn.lock
Labels: electron

#10175 Minor GWT source file cleanup
  src/gwt/src/org/rstudio/core/client/widget/LeftRightToggleButton.java
  src/gwt/src/org/rstudio/core/client/widget/SmallButton.java
  src/gwt/src/org/rstudio/core/client/widget/ThemedButton.java
  src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/common/StudioClientCommonConstants.java
  src/gwt/src/org/rstudio/studio/client/common/vcs/VCSConstants.java
  src/gwt/src/org/rstudio/studio/client/projects/StudioClientProjectConstants.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateOptionsDialog.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/RsconnectConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/MainSplitPanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionPopupPanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants.java
Labels: developer

#10177 Use pullBuildPush for windows as well
  Jenkinsfile
Labels: builds

#10184 Fix Electron desktop on Windows (blank window)
  src/node/desktop/src/core/array-utils.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/renderer/preload.ts
  src/node/desktop/test/unit/core/array-utils.test.ts
Labels: electron

#10197 feat(i18n): views-environment
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/ClearAllDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/ViewEnvironmentConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/ViewEnvironmentConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportFileChooser.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsvLocale.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiSav.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/ImportFileSettingsDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/model/MemoryStat.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/CallFrameItem.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/CallFramePanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectGrid.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/MemUsageWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/MemoryUsagePieChart.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/MemoryUsageSummary.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/MemoryUsageSummaryDialog.java
Labels: locale

#10206 feat(i18n): views-vcs
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/AddRemoteDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/BranchToolbarButton.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/CreateBranchDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/CreateBranchToolbarButton.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/HistoryBranchToolbarButton.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/ViewVcsConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/ViewVcsConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ChangelistTable.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/Pager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/diff/LineTableView.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitDetail.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitFilterToolbarButton.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitListTable.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/DiffFrame.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/HistoryAsyncDataProvider.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/HistoryPanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/HistoryPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/SizeWarningWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/graph/GraphLine.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitChangelistTable.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitChangelistTablePresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPresenterCore.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitStatusRenderer.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/model/GitState.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNChangelistTable.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNCommandHandler.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNResolveDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNSelectChangelistTable.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNSelectChangelistTablePresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNStatusRenderer.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/commit/SVNCommitDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/dialog/SVNHistoryStrategy.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/dialog/SVNReviewPanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/dialog/SVNReviewPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/model/SVNState.java
Labels: locale

#10220 add API for bug reporting
  src/cpp/r/R/Api.R
  src/cpp/r/R/Tools.R
Labels: developer

#10225 fix General tab label on global prefs
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Labels: locale

#10231 feat(i18n): enable fr locale support
  src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
  src/gwt/src/org/rstudio/studio/RStudioDesktopSuperDevMode.gwt.xml
  src/gwt/src/org/rstudio/studio/RStudioSuperDevMode.gwt.xml
  src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/common/StudioClientCommonConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/common/StudioClientCommonConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/projects/StudioClientProjectConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/quarto/QuartoConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/RsconnectConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/ClientWorkbenchConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialConstants.java
Labels: locale

#10256 support for R graphics engine 15 (#10058)
  NEWS.md
  src/cpp/r/include/r/session/RSession.hpp
  src/cpp/r/session/graphics/RGraphicsDevDesc.cpp
  src/cpp/r/session/graphics/RGraphicsDevDesc.hpp
  src/cpp/r/session/graphics/RGraphicsDevDescVersions.hpp
  src/cpp/session/include/session/SessionOptions.gen.hpp
  src/cpp/session/session-options.json
Labels: plots, backport

#10229 fix(i18n): clean-up literals and i18n-ify missed literals
  src/gwt/src/org/rstudio/studio/client/RStudio.java
  src/gwt/src/org/rstudio/studio/client/StudioClientConstants.java
  src/gwt/src/org/rstudio/studio/client/StudioClientConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants.java
  src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/application/ui/RTimeoutOptions.java
  src/gwt/src/org/rstudio/studio/client/application/ui/RequestLogVisualization.java
  src/gwt/src/org/rstudio/studio/client/htmlpreview/HTMLPreviewPresenter.java
  src/gwt/src/org/rstudio/studio/client/htmlpreview/HtmlPreviewConstants.java
  src/gwt/src/org/rstudio/studio/client/htmlpreview/HtmlPreviewConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/htmlpreview/HtmlPreviewConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewProgressDialog.java
  src/gwt/src/org/rstudio/studio/client/notebook/CompileNotebookOptionsDialog.java
  src/gwt/src/org/rstudio/studio/client/palette/PaletteConstants.java
  src/gwt/src/org/rstudio/studio/client/palette/PaletteConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/palette/PaletteConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/palette/ui/UserPrefPaletteEntry.java
  src/gwt/src/org/rstudio/studio/client/quarto/QuartoConstants.java
  src/gwt/src/org/rstudio/studio/client/quarto/QuartoConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/quarto/QuartoConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/quarto/ui/NewQuartoDocumentDialog.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/RMarkdownConstants.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/RMarkdownConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/rmarkdown/RMarkdownConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/RSConnect.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/RsconnectConstants.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/RsconnectConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/RsconnectConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/server/ServerConstants.java
  src/gwt/src/org/rstudio/studio/client/server/ServerConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/server/ServerConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServerAuth.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/UIConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/UIConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchTabPanel.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsolePane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/ViewEnvironmentConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/ViewEnvironmentConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportColumnTypesMenu.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerPresenter.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/MarkdownToolbar.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCppHelper.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetRMarkdownHelper.java
Labels: locale

#10253 Feature/add more fr locales and clean-up unused properties
  src/gwt/src/org/rstudio/studio/client/StudioClientConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/projects/StudioClientProjectConstants.java
  src/gwt/src/org/rstudio/studio/client/projects/StudioClientProjectConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/RsconnectConstants.java
  src/gwt/src/org/rstudio/studio/client/rsconnect/RsconnectConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishReportSourcePage.java
  src/gwt/src/org/rstudio/studio/client/workbench/ClientWorkbenchConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/addins/AddinsConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/codesearch/CodeSearchConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlotConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/model/ModelConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/snippets/SnippetsConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/ui/UIConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/ViewBuildtoolsConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/choosefile/ChoosefileConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ConnectionsConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ConnectionsConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/edit/EditConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/ViewEnvironmentConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/history/HistoryConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/JobsConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/OutputConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/plots/PlotsConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/presentation/PresentationConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/presentation2/Presentation2Constants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/ViewVcsConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/ViewVcsConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerConstants_fr.properties
Labels: locale
