Repository rstudio/rstudio, pull requests merged in 2021-06, with the labels that each got.

#9433 Fix electron unit tests on Windows
  src/node/desktop/.eslintrc.js
  src/node/desktop/package.json
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/src/core/system.ts
  src/node/desktop/src/core/xdg.ts
  src/node/desktop/src/main/desktop-utils.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/test/core/file-path.spec.ts
  src/node/desktop/test/core/xdg.spec.ts
  src/node/desktop/test/main/app.spec.ts
  src/node/desktop/test/main/desktop-utils.spec.ts
  src/node/desktop/test/main/main.spec.ts
  src/node/desktop/yarn.lock
Labels: automation, electron

#9419 avoid deparsing excessively large calls
  src/cpp/r/R/Options.R
  src/cpp/session/modules/SessionCodeTools.R
  src/cpp/session/modules/SessionEnvironment.R
  src/cpp/tests/testthat/test-debugger.R
Labels: debugging

#9432 consolidate FilePathTests into a single location
  src/cpp/core/FilePathTests.cpp
  src/cpp/shared_core/FilePathTests.cpp
Labels: automation

#9442 more tests, eslint cleanup
  src/node/desktop/.mocharc.json
  src/node/desktop/package.json
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/src/core/log-options.ts
  src/node/desktop/src/core/system.ts
  src/node/desktop/src/main/app.ts
  src/node/desktop/src/main/desktop-utils.ts
  src/node/desktop/src/main/init.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/test/core/environment.test.ts
  src/node/desktop/test/core/err.test.ts
  src/node/desktop/test/core/file-path.test.ts
  src/node/desktop/test/core/log.test.ts
  src/node/desktop/test/core/system.test.ts
  src/node/desktop/test/core/user.test.ts
  src/node/desktop/test/core/xdg.test.ts
  src/node/desktop/test/main/app.test.ts
  src/node/desktop/test/main/desktop-utils.test.ts
  src/node/desktop/test/main/init.test.ts
  src/node/desktop/test/main/main.test.ts
  src/node/desktop/yarn.lock
Labels: electron

#9448 Moved location of Python global and project options to make it more prominent
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialog.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.java
Labels: enhancement, python, user preferences

#9457 implement basic packaging of Electron app
  src/node/desktop/.gitignore
  src/node/desktop/package.json
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/test/main/utils.test.ts
  src/node/desktop/yarn.lock
Labels: developer, electron

#9447 implement createAliasedPath
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/test/core/file-path.test.ts
  src/node/desktop/tsconfig.json
Labels: electron

#9467 move unit tests into tests/unit subfolder
  src/node/desktop/test/unit/core/environment.test.ts
  src/node/desktop/test/unit/core/err.test.ts
  src/node/desktop/test/unit/core/file-path.test.ts
  src/node/desktop/test/unit/core/log.test.ts
  src/node/desktop/test/unit/core/system.test.ts
  src/node/desktop/test/unit/core/user.test.ts
  src/node/desktop/test/unit/core/xdg.test.ts
  src/node/desktop/test/unit/main/app.test.ts
  src/node/desktop/test/unit/main/main.test.ts
  src/node/desktop/test/unit/main/utils.test.ts
Labels: developer, electron

#9469 Initial skeleton for Spectron-based integration tests
  src/node/desktop/package.json
  src/node/desktop/test/integration/mocharc.json
  src/node/desktop/test/integration/startup.int.ts
  src/node/desktop/test/unit/mocharc.json
  src/node/desktop/yarn.lock
Labels: automation, electron

#9446 make Shift+Command+Zero the sole shortcut for restartR on Mac
  NEWS.md
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
  src/gwt/www/docs/keyboard.htm
Labels: keyboard shortcuts, macos

#9472 install reticulate before running Python chunks
  NEWS.md
  src/gwt/src/org/rstudio/studio/client/rmarkdown/model/NotebookDocQueue.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/NotebookQueueState.java
Labels: notebooks, python

#9491 fix command for showing configure-build-tools pane
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialog.java
Labels: projects, regression

#9493 remove spectron
  src/node/desktop/package.json
  src/node/desktop/test/integration/mocharc.json
  src/node/desktop/test/integration/startup.int.ts
  src/node/desktop/yarn.lock
Labels: automation, electron

#9485 Add barebones internationalization support
  src/gwt/.gitignore
  src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
  src/gwt/src/org/rstudio/studio/RStudioDesktopSuperDevMode.gwt.xml
  src/gwt/src/org/rstudio/studio/RStudioSuperDevMode.gwt.xml
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialog.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogConstants.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogMessages.java
  src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogMessages_en.properties
  src/gwt/tools/i18n-helpers/README.md
  src/gwt/tools/i18n-helpers/create_dev_locale.sh
Labels: locale

#9498 Add support for high DPI plots on RStudio Server
  NEWS.md
  src/gwt/src/org/rstudio/core/client/BrowseCap.java
  src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
Labels: plots

#9492 various enhancements to python integration
  NEWS.md
  src/cpp/r/include/r/session/RSession.hpp
  src/cpp/r/session/RInit.cpp
  src/cpp/r/session/RStdCallbacks.cpp
  src/cpp/session/SessionMain.cpp
  src/cpp/session/include/session/SessionModuleContext.hpp
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/modules/SessionPythonEnvironments.R
  src/cpp/session/modules/SessionPythonEnvironments.cpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/core/client/ElementIds.java
  src/gwt/src/org/rstudio/core/client/widget/FileChooserTextBox.java
  src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
  src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPythonPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPaneBase.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterSelectionDialog.java
Labels: python

#9506 tell 7z to overwrite without prompting when extracting soci.tar.gz
  dependencies/windows/install-soci/install-soci.R
Labels: builds

#9514 implement session startup (Posix-only)
  src/node/desktop/package.json
  src/node/desktop/src/core/environment.ts
  src/node/desktop/src/main/activation-overlay.ts
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-callback.ts
  src/node/desktop/src/main/detect_r.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/menu-callback.ts
  src/node/desktop/src/main/pending-window.ts
  src/node/desktop/src/main/r-command-evaluator.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/renderer/desktop-bridge.ts
  src/node/desktop/src/renderer/desktop-info-bridge.ts
  src/node/desktop/src/renderer/menu-bridge.ts
  src/node/desktop/src/renderer/preload.ts
  src/node/desktop/yarn.lock
Labels: developer, electron

#9516 fix eslint warnings in Electron project
  src/node/desktop/src/main/desktop-callback.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/menu-callback.ts
  src/node/desktop/src/renderer/desktop-bridge.ts
  src/node/desktop/test/unit/main/detect_r.test.ts
Labels: developer, electron

#9505 automatically activate .condaenv environments; fixes for reticulate binding to Anaconda
  src/cpp/core/r_util/REnvironmentPosix.cpp
  src/cpp/core/r_util/RProjectFile.cpp
  src/cpp/desktop/DesktopSessionLauncher.cpp
  src/cpp/r/R/Tools.R
  src/cpp/session/SessionMain.cpp
  src/cpp/session/modules/SessionPythonEnvironments.R
  src/cpp/session/projects/SessionProjects.cpp
Labels: python

#9520 resolve TODOs: generate launcher token and port for Electron desktop
  src/node/desktop/NOTICE.electron
  src/node/desktop/package.json
  src/node/desktop/src/core/system.ts
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-callback.ts
  src/node/desktop/src/main/detect_r.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/main/menu-callback.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/test/unit/core/system.test.ts
  src/node/desktop/test/unit/main/application.test.ts
  src/node/desktop/test/unit/main/session-launcher.test.ts
  src/node/desktop/yarn.lock
Labels: developer, electron

#9527 create basic interface for logging and a simple console logger
  src/node/desktop/src/core/console-logger.ts
  src/node/desktop/src/core/core-state.ts
  src/node/desktop/src/core/environment.ts
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/src/core/logger.ts
  src/node/desktop/src/core/xdg.ts
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-callback.ts
  src/node/desktop/src/main/detect_r.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/test/unit/core/console-logger.test.ts
  src/node/desktop/test/unit/core/core-state.test.ts
  src/node/desktop/test/unit/core/file-path.test.ts
  src/node/desktop/test/unit/core/logger.test.ts
Labels: electron, logging

#9524 remove duplicate entry for importDatasetFromSAV command
  src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Labels: data import

#9528 use Sinon.JS to fake console.log in logging tests
  src/node/desktop/package.json
  src/node/desktop/test/unit/core/console-logger.test.ts
  src/node/desktop/yarn.lock
Labels: automation, electron

#9529 implement basic support for LogLevels
  src/node/desktop/src/core/console-logger.ts
  src/node/desktop/src/core/core-state.ts
  src/node/desktop/src/core/logger.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/test/unit/core/console-logger.test.ts
  src/node/desktop/test/unit/core/file-path.test.ts
Labels: electron, logging

#9522 use separate tabs for different Python types
  src/cpp/session/modules/SessionPythonEnvironments.R
  src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPaneBase.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterListEntryUi.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterSelectionDialog.java
Labels: python

#9533 fix diagnostics logging, other Electron WIP
  src/node/desktop/src/core/console-logger.ts
  src/node/desktop/src/core/core-state.ts
  src/node/desktop/src/core/logger.ts
  src/node/desktop/src/main/activation-overlay.ts
  src/node/desktop/src/main/application-launch.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/detect_r.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/gwt-window.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/rstudio-browser-window.ts
  src/node/desktop/src/main/satellite-window.ts
  src/node/desktop/src/main/secondary-window.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/test/unit/core/console-logger.test.ts
  src/node/desktop/test/unit/core/file-path.test.ts
  src/node/desktop/test/unit/main/activation-overlay.test.ts
  src/node/desktop/test/unit/main/application-launch.test.ts
  src/node/desktop/test/unit/main/gwt-callback.test.ts
  src/node/desktop/test/unit/main/main-window.test.ts
  src/node/desktop/test/unit/main/menu-callback.test.ts
  src/node/desktop/test/unit/main/pending-window.test.ts
Labels: developer, electron

#9531 tweak ordering of library() completion results
  NEWS.md
  src/cpp/session/modules/SessionRCompletions.R
Labels: autocompletion

#9549 Implement minimal windows, more WIP on other aspects
  src/node/desktop/.gitignore
  src/node/desktop/docs/ElectronWindowClasses.puml
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/menu-callback.ts
  src/node/desktop/src/main/minimal-window.ts
  src/node/desktop/src/main/window-tracker.ts
  src/node/desktop/src/renderer/desktop-bridge.ts
  src/node/desktop/src/renderer/desktop-info-bridge.ts
  src/node/desktop/src/renderer/menu-bridge.ts
  src/node/desktop/test/unit/main/minimal-window.test.ts
  src/node/desktop/test/unit/main/window-tracker.test.ts
Labels: developer, electron

#9550 wire MainWindow into window class hierarchy (Electron)
  src/node/desktop/src/main/activation-overlay.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/gwt-window.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/minimal-window.ts
  src/node/desktop/src/main/secondary-window.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/main/window-tracker.ts
  src/node/desktop/test/unit/main/desktop-browser-window.test.ts
  src/node/desktop/test/unit/main/gwt-callback.test.ts
  src/node/desktop/test/unit/main/gwt-window.test.ts
  src/node/desktop/test/unit/main/menu-callback.test.ts
  src/node/desktop/test/unit/main/minimal-window.test.ts
  src/node/desktop/test/unit/main/satellite-window.test.ts
  src/node/desktop/test/unit/main/secondary-window.test.ts
  src/node/desktop/test/unit/main/window-tracker.test.ts
  src/node/desktop/test/unit/unit-utils.ts
  src/node/desktop/yarn.lock
Labels: developer, electron
