Repository rstudio/rstudio, pull requests merged in 2021-03, with the labels that each got.

#9085 make GWT detect both Electron and QtWebEngine desktop user agents
  src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
Labels: electron

#9080 Report verify-installation failure to stderr
  NEWS.md
  src/cpp/server/ServerMain.cpp
Labels: support

#9104 initial dev-container definition
  .devcontainer/devcontainer.json
Labels: developer

#9110 avoid using lipo (requires CLT installed)
  src/cpp/core/system/Architecture.cpp
Labels: macos

#9115 avoid crashes when logging default-constructed error objects
  NEWS.md
  src/cpp/core/MiscellaneousTests.cpp
  src/cpp/r/session/graphics/RGraphicsPlotManager.cpp
  src/cpp/shared_core/Error.cpp
  src/cpp/shared_core/include/shared_core/Error.hpp
Labels: shared_core

#9099 Add option to report R session version
  NEWS.md
  src/cpp/session/SessionMain.cpp
  src/cpp/session/SessionOptions.cpp
  src/cpp/session/include/session/SessionConstants.hpp
  src/cpp/session/include/session/SessionOptions.gen.hpp
  src/cpp/session/session-options.json
Labels: support

#9129 Improve RStudio startup diagnostics
  NEWS.md
  src/cpp/desktop/DesktopSessionLauncher.cpp
  src/cpp/desktop/desktop-config.h.in
  src/cpp/desktop/html/error.html
Labels: desktop, desktop integration

#9122 fixups for Rtools 4.0
  src/cpp/core/r_util/RToolsInfo.cpp
  src/cpp/session/modules/clang/RCompilationDatabase.cpp
Labels: rtools

#9150 vscode extension recommendations
  .devcontainer/devcontainer.json
  .gitignore
  .vscode/extensions.json
  src/.gitignore
Labels: developer

#9146 Add session-suspend-on-incomplete-statement option
  NEWS.md
  src/cpp/r/include/r/session/RSession.hpp
  src/cpp/r/session/RSession.cpp
  src/cpp/session/SessionMain.cpp
  src/cpp/session/include/session/SessionConstants.hpp
  src/cpp/session/include/session/SessionOptions.gen.hpp
  src/cpp/session/session-options.json
Labels: server

#9167 Move Hash.cpp/hpp from core to shared_core
  src/cpp/core/CMakeLists.txt
  src/cpp/core/Hash.cpp
  src/cpp/core/http/Response.cpp
  src/cpp/core/include/core/Hash.hpp
  src/cpp/core/system/System.cpp
  src/cpp/session/SessionModuleContext.cpp
  src/cpp/session/SessionSourceDatabase.cpp
  src/cpp/session/modules/SessionPackrat.cpp
  src/cpp/session/modules/clang/RCompilationDatabase.cpp
  src/cpp/session/modules/panmirror/SessionPanmirrorBibliography.cpp
  src/cpp/session/modules/zotero/ZoteroCollections.cpp
  src/cpp/session/modules/zotero/ZoteroCollectionsLocal.cpp
  src/cpp/shared_core/CMakeLists.txt
  src/cpp/shared_core/Hash.cpp
  src/cpp/shared_core/include/shared_core/Hash.hpp
Labels: developer

#9171 Add recursion guard for notebook console output
  src/cpp/session/modules/rmarkdown/NotebookExec.cpp
  src/cpp/session/modules/rmarkdown/NotebookExec.hpp
Labels: notebooks

#9174 re-enable unit tests for macOS
  Jenkinsfile.macos
  src/cpp/CMakeLists.txt
  src/cpp/rstudio-tests.in
  src/cpp/tests/testthat/run-tests.R
Labels: test
