Repository rstudio/rstudio, pull requests merged in 2021-05, with the labels that each got.

#9300 debugger: handle NULLs in function calls appropriately
  src/cpp/r/RExec.cpp
  src/cpp/session/modules/SessionEnvironment.R
  src/cpp/session/modules/SessionObjectExplorer.R
Labels: debugging

#9356 show memory usage as mebibytes
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/MemoryUsageSummary.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/MemoryUsageSummary.ui.xml
Labels: environment pane

#9365 improve handling of malformed data.frame in viewer
  NEWS.md
  src/cpp/core/StringUtils.cpp
  src/cpp/core/StringUtilsTests.cpp
  src/cpp/core/include/core/StringUtils.hpp
  src/cpp/session/modules/data/DataViewer.cpp
Labels: data viewer

#9368 Put the Electron prototype in a place it can be used for infrastructure work
  src/node/prototype/.gitignore
  src/node/prototype/README.md
  src/node/prototype/package.json
  src/node/prototype/src/main/app.ts
  src/node/prototype/src/main/desktop-callback.ts
  src/node/prototype/src/main/desktop-info.ts
  src/node/prototype/src/main/main-window.ts
  src/node/prototype/src/main/main.ts
  src/node/prototype/src/main/menu-callback.ts
  src/node/prototype/src/main/pending-window.ts
  src/node/prototype/src/main/r-command-evaluator.ts
  src/node/prototype/src/main/session-launcher.ts
  src/node/prototype/src/renderer/desktop-bridge.ts
  src/node/prototype/src/renderer/desktop-info-bridge.ts
  src/node/prototype/src/renderer/menu-bridge.ts
  src/node/prototype/src/renderer/preload.ts
  src/node/prototype/tsconfig.json
  src/node/prototype/yarn.lock
Labels: developer

#9369 don't auto-detect indentation by default
  NEWS.md
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Labels: source editor

#9371 update dependency paths in development conf files
  src/cpp/RScriptCallbacks.hpp
  src/cpp/conf/rdesktop-dev.conf
  src/cpp/conf/rsession-dev.conf
  src/cpp/session/CMakeLists.txt
Labels: developer

#9378 implement basic R version scanning
  src/node/prototype/src/main/main.ts
  src/node/prototype/src/main/r.ts
Labels: electron

#9375 scope Sys.setlocale() workaround to R < 3.5.2
  NEWS-v1.4-juliet-rose.md
  src/cpp/session/modules/SessionCodeTools.R
Labels: source editor

#9383 find system Python installations on Windows
  src/cpp/session/modules/SessionPythonEnvironments.R
Labels: python

#9386 support autocompletion for native pipe
  src/cpp/session/modules/SessionRCompletions.R
  src/gwt/acesupport/acemode/r_code_model.js
Labels: autocompletion

#9403 ensure Python installations can be discovered when no Python on PATH
  src/cpp/session/modules/SessionPythonEnvironments.R
Labels: python

#9410 initial bits and pieces of Electron project
  src/node/desktop/.gitignore
  src/node/desktop/.prettierrc
  src/node/desktop/package.json
  src/node/desktop/src/core/environment.ts
  src/node/desktop/src/core/err.ts
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/src/core/log-options.ts
  src/node/desktop/src/core/log.ts
  src/node/desktop/src/core/system.ts
  src/node/desktop/src/core/user.ts
  src/node/desktop/src/core/xdg.ts
  src/node/desktop/src/main/desktop-utils.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/main/product-info.ts
  src/node/desktop/src/renderer/preload.ts
  src/node/desktop/test/core/environment.spec.ts
  src/node/desktop/test/core/err.spec.ts
  src/node/desktop/test/core/file-path.spec.ts
  src/node/desktop/test/core/log.spec.ts
  src/node/desktop/test/core/system.spec.ts
  src/node/desktop/test/core/user.spec.ts
  src/node/desktop/test/core/xdg.spec.ts
  src/node/desktop/test/main/main.spec.ts
  src/node/desktop/tsconfig.json
  src/node/desktop/yarn.lock
Labels: electron

#9416 avoid using py_run_string(..., local = TRUE)
  src/cpp/session/modules/SessionReticulate.R
Labels: python

#9422 show component info when IDE launched with --version switch
  src/node/desktop/package.json
  src/node/desktop/src/main/main.ts
  src/node/desktop/tsconfig.json
Labels: electron

#9428 hookup eslint and fix all errors in Electron project sources
  src/node/desktop/.eslintignore
  src/node/desktop/.eslintrc.js
  src/node/desktop/.npmrc
  src/node/desktop/.prettierrc
  src/node/desktop/package.json
  src/node/desktop/src/core/environment.ts
  src/node/desktop/src/core/file-path.ts
  src/node/desktop/src/core/log-options.ts
  src/node/desktop/src/core/system.ts
  src/node/desktop/src/core/user.ts
  src/node/desktop/src/core/xdg.ts
  src/node/desktop/src/main/app.ts
  src/node/desktop/src/main/desktop-utils.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/src/main/product-info.ts
  src/node/desktop/test/core/environment.spec.ts
  src/node/desktop/test/core/err.spec.ts
  src/node/desktop/test/core/file-path.spec.ts
  src/node/desktop/test/core/log.spec.ts
  src/node/desktop/test/core/system.spec.ts
  src/node/desktop/test/core/user.spec.ts
  src/node/desktop/test/core/xdg.spec.ts
  src/node/desktop/yarn.lock
Labels: electron

#9430 add NOTICE.electron to track new components added for Electron desktop
  src/node/desktop/NOTICE.electron
Labels: electron

#9431 execute shared_core unit tests on Windows via rstudio-tests.bat
  src/cpp/rstudio-tests.bat.in
Labels: automation
