Repository rstudio/rstudio, pull requests merged in 2022-02, with the labels that each got.

#10372 feat(i18n): Shortcuts
  src/gwt/src/org/rstudio/core/client/CoreClientConstants.java
  src/gwt/src/org/rstudio/core/client/CoreClientConstants_en.properties
  src/gwt/src/org/rstudio/core/client/CoreClientConstants_fr.properties
  src/gwt/src/org/rstudio/core/client/command/KeyCombination.java
  src/gwt/src/org/rstudio/core/client/widget/ShortcutInfoPanel.java
  src/gwt/src/org/rstudio/studio/client/palette/PaletteConstants.java
  src/gwt/src/org/rstudio/studio/client/palette/PaletteConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/palette/PaletteConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/palette/ui/CommandPaletteCommand.java
Labels: locale

#10495 make-package.bat options cleanup
  package/win32/clean-build.bat
  package/win32/make-install-win32.bat
  package/win32/make-package.bat
Labels: developer

#10498 delete unused scripts (Electron)
  src/node/desktop/scripts/import-resources.ts
  src/node/desktop/scripts/mac-package
  src/node/desktop/scripts/update-yarn
Labels: electron

#10519 Fix Electron recent menu items
  src/gwt/src/org/rstudio/studio/client/workbench/MRUList.java
Labels: electron

#10536 stamp version into Electron app (macOS)
  package/osx/make-package
  src/node/desktop/scripts/update-json-version.sh
Labels: electron

#10533 Fix duplicate menu separators
  src/node/desktop/.eslintrc.js
  src/node/desktop/src/main/menu-callback.ts
  src/node/desktop/test/unit/main/menu-callback.test.ts
Labels: electron

#10557 Include build info in Electron app
  package/osx/make-package
  src/node/desktop/CMakeLists.txt
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/build-info.ts
  src/node/desktop/src/main/build-info.ts.in
  src/node/desktop/src/main/product-info.ts
  src/node/desktop/src/main/session-launcher.ts
  src/node/desktop/src/main/utils.ts
  src/node/desktop/test/unit/main/build-info.test.ts
Labels: electron

#10566 Implement Electron package building on Windows
  CMakeGlobals.txt
  package/linux/make-desktop-package
  package/linux/make-electron-package
  package/linux/make-package
  package/osx/make-package
  package/win32/CMakeLists.txt
  package/win32/cmake/modules/.gitignore
  package/win32/cmake/modules/NSIS.template.in.electron
  package/win32/cmake/modules/NSIS.template.in.qt
  package/win32/make-install-win32.bat
  package/win32/make-package.bat
  src/cpp/CMakeLists.txt
  src/cpp/desktop/CMakeLists.txt
  src/node/CMakeNodeTools.txt
  src/node/desktop/CMakeLists.txt
  src/node/desktop/package.json
  src/node/desktop/scripts/package-helper.ts
Labels: electron

#10572 Build Electron Desktop for Windows
  Jenkinsfile
  package/win32/make-package.bat
Labels: builds, electron

#10604 Removed Debug flag for i18next
  src/node/desktop/src/main/i18n-manager.ts
Labels: electron

#10546 Update Catch2 to v2.13.8
  src/cpp/tests/cpp/tests/vendor/catch.hpp
Labels: automation

#10611 Package build for Linux Electron (Ubuntu18+ for first try)
  CMakeGlobals.txt
  Jenkinsfile
  package/linux/CMakeLists.txt
  package/linux/debian-control/postinst-electron.in
  package/linux/debian-control/postrm-electron.in
  package/linux/make-desktop-package
  package/linux/make-electron-package
  package/linux/make-package
  package/linux/rpm-script/postinst-electron.sh.in
  package/linux/rpm-script/postrm-electron.sh.in
  src/node/desktop/CMakeLists.txt
Labels: electron

#10615 update links to contributor pdfs and email to use
  CONTRIBUTING.md
Labels: documentation

#10634 Update node toolchain to v16.14.0
  dependencies/common/install-node
  dependencies/tools/rstudio-tools.cmd
  dependencies/tools/rstudio-tools.sh
  package/linux/make-package
  src/gwt/build.xml
  src/node/CMakeNodeTools.txt
Labels: builds

#10640 install x64 and M1 node via dependency scripts on MacOS
  dependencies/common/install-node
  dependencies/common/install-npm-dependencies
  dependencies/common/install-yarn
  dependencies/osx/install-dependencies-osx-arch
  dependencies/tools/rstudio-tools.sh
  package/osx/cmake/merge-electron.cmake
  package/osx/make-package
  src/node/CMakeNodeTools.txt
Labels: builds, electron

#10620 stop using yarn for Electron
  package/linux/make-package
  package/osx/cmake/merge-electron.cmake
  package/osx/make-package
  package/osx/scripts/package-lock.json
  package/osx/scripts/yarn.lock
  package/win32/make-package.bat
  src/node/CMakeNodeTools.txt
  src/node/desktop/.npmrc
  src/node/desktop/CMakeLists.txt
  src/node/desktop/README.md
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
  src/node/desktop/yarn.lock
Labels: electron

#10601 implement back / forward mouse handlers
  src/cpp/session/modules/SessionHelp.cpp
  src/gwt/src/org/rstudio/core/client/BrowseCap.java
  src/gwt/src/org/rstudio/core/client/Debug.java
  src/gwt/src/org/rstudio/core/client/dom/EventProperty.java
  src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
Labels: electron

#10646 Electron Packages Update
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
Labels: electron

#10663 Fixes for secondary/satellite window creation (Electron)
  src/node/desktop/forge.config.js
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
  src/node/desktop/src/assets/locales/en.json
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/satellite-window.ts
  src/node/desktop/src/main/secondary-window.ts
  src/node/desktop/webpack.main.config.js
Labels: electron

#10668 Hide menubar on secondary windows
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-window.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/minimal-window.ts
  src/node/desktop/src/main/satellite-window.ts
  src/node/desktop/src/main/secondary-window.ts
  src/node/desktop/test/unit/main/desktop-browser-window.test.ts
  src/node/desktop/test/unit/main/gwt-window.test.ts
  src/node/desktop/test/unit/main/minimal-window.test.ts
  src/node/desktop/test/unit/main/window-tracker.test.ts
Labels: electron

#10675 Setting Relative Imports as Default on VSCode
  src/node/desktop/.vscode/settings.json
Labels: electron

#10681 Enable electron build for RHEL8
  Jenkinsfile
  docker/jenkins/Dockerfile.rhel8-x86_64
Labels: electron

#10686 update electron 17.1.0
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
Labels: electron

#10685 use objects as constructor args (electron)
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/gwt-window.ts
  src/node/desktop/src/main/main-window.ts
  src/node/desktop/src/main/minimal-window.ts
  src/node/desktop/src/main/satellite-window.ts
  src/node/desktop/src/main/secondary-window.ts
  src/node/desktop/test/unit/main/desktop-browser-window.test.ts
  src/node/desktop/test/unit/main/gwt-window.test.ts
  src/node/desktop/test/unit/main/minimal-window.test.ts
  src/node/desktop/test/unit/main/window-tracker.test.ts
Labels: electron

#10697 enable Electron builds for opensuse15 and centos7
  Jenkinsfile
  docker/jenkins/Dockerfile.centos7-x86_64
  docker/jenkins/Dockerfile.opensuse15-x86_64
Labels: electron
