Repository rstudio/rstudio, pull requests merged in 2022-04, with the labels that each got.

#10886 Update to Electron 18.0.1
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
  src/node/desktop/src/main/desktop-browser-window.ts
Labels: electron

#10921 Move where events are added on chunks to maintain scrolling fix on pages
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputFrame.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
Labels: bug, r markdown

#10943 Remove proof-of-concept Playwright tests
  src/node/desktop/CMakeLists.txt
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
  src/node/desktop/test/int/console.ts
  src/node/desktop/test/int/int-utils.ts
  src/node/desktop/test/int/mocharc.json
  src/node/desktop/test/int/session-restart.test.ts
  src/node/desktop/test/int/startup-fail-session.test.ts
  src/node/desktop/test/int/startup.test.ts
  src/node/desktop/test/int/utility-window.test.ts
Labels: electron

#10956 remove unused code and fix a unit test
  src/node/desktop/src/main/app-state.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/test/unit/core/file-path.test.ts
Labels: electron

#10961 upgrade to Electron 18.0.3
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
Labels: electron

#10960 Fix accessible keyboard shortcut help for Electron
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/main/utils.ts
Labels: electron

#10970 build Electron on Debian10
  Jenkinsfile
  docker/jenkins/Dockerfile.debian10-x86_64
Labels: builds

#10972 install xvfb for electron unit tests
  docker/jenkins/Dockerfile.debian10-x86_64
Labels: electron

#11000 update Electron to 18.0.4
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
Labels: electron

#11002 eliminate warnings from Electron unit tests
  src/node/desktop/test/unit/core/file-path.test.ts
  src/node/desktop/test/unit/core/xdg.test.ts
  src/node/desktop/test/unit/main/menu-callback.test.ts
Labels: automation, electron

#11064 upgrade to Electron 18.1.0
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
Labels: electron

#11066 install cmake 3.19.8 on builders
  package/linux/install-dependencies
Labels: builds

#11077 install same cmake for debian10 used by other Linux builds
  docker/jenkins/Dockerfile.debian10-x86_64
Labels: builds

#11084 Stop building obsolete/unnecessary platforms
  Jenkinsfile
Labels: builds

#11085 remove dockerfiles and dep script for obsolete platforms
  dependencies/linux/install-dependencies-stretch
  docker/jenkins/Dockerfile.debian10-x86_64
  docker/jenkins/Dockerfile.debian9-x86_64
  docker/jenkins/Dockerfile.opensuse-x86_64
Labels: builds
