Repository rstudio/rstudio, pull requests merged in 2022-06, with the labels that each got.

#11333 Fix Electron renderer crash on macOS during Quarto editing
  package/osx/cmake/codesign-package-electron.cmake
  package/osx/entitlements-electron.plist
Labels: electron

#11353 run mac unit tests in x64 terminal
  Jenkinsfile.macos
  Jenkinsfile.macos.electron
Labels: automation

#11324 i18n: desktop locales
  src/node/desktop/src/assets/locales/fr.json
Labels: locale

#11355 using python3 in unit test
  src/cpp/core/system/ProcessTests.cpp
Labels: automation

#11371 Fix path encoding when opening files on Windows (Electron)
  src/node/desktop/src/renderer/desktop-bridge.ts
  src/node/desktop/tsconfig.json
Labels: electron

#11397 delete unused devicePixelRatio gwt callback
  src/node/desktop/src/main/gwt-callback.ts
  src/node/desktop/src/renderer/desktop-bridge.ts
Labels: electron

#11509 Use latest TypeScript for Electron project
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
Labels: developer, electron
