Repository rstudio/rstudio, pull requests merged in 2022-05, with the labels that each got.

#11090 Add Session Server RPC to open source
  src/cpp/core/CMakeLists.txt
  src/cpp/core/SocketRpc.cpp
  src/cpp/core/include/core/SocketRpc.hpp
  src/cpp/server/CMakeLists.txt
  src/cpp/server/ServerMain.cpp
  src/cpp/server/ServerSessionManager.cpp
  src/cpp/server/ServerSessionRpc.cpp
  src/cpp/server/ServerSessionRpc.hpp
  src/cpp/server/ServerSessionRpcOverlay.cpp
  src/cpp/server/include/server/ServerPaths.hpp
  src/cpp/session/CMakeLists.txt
  src/cpp/session/SessionMain.cpp
  src/cpp/session/SessionServerRpc.cpp
  src/cpp/session/SessionServerRpcOverlay.cpp
  src/cpp/session/include/session/SessionServerRpc.hpp
  src/cpp/session/modules/SessionOverlay.R
Labels: r session

#11193 remove unused gwt class replacements
  src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
Labels: developer

#11214 Fix flags not being passed through constructor in R version selectors
  NEWS.md
  src/gwt/src/org/rstudio/studio/client/application/ui/RVersionSelectWidget.java
Labels: regression, r versions, support

#11223 fedora-36 specific unit test fix
  src/cpp/rstudio-tests.in
Labels: automation

#11293 use Qt 5.12.10 on MacOS
  dependencies/osx/install-qt-macos
Labels: developer

#11320 localization diff tool
  src/gwt/tools/locdiff/.eslintrc.cjs
  src/gwt/tools/locdiff/.gitignore
  src/gwt/tools/locdiff/README.md
  src/gwt/tools/locdiff/locdiff.js
  src/gwt/tools/locdiff/package-lock.json
  src/gwt/tools/locdiff/package.json
Labels: locale
