Repository rstudio/rstudio, pull requests merged in 2022-03, with the labels that each got.

#10753 Unit test fixes, accomodate nogroup vs nobody
  src/cpp/core/system/PosixSystemTests.cpp
  src/cpp/rstudio-tests.in
Labels: automation

#10759 upgrade Electron to 17.1.1
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
Labels: electron

#10805 Enable Electron unit tests for Linux/Bionic build
  Jenkinsfile
  docker/jenkins/Dockerfile.bionic-amd64
  src/node/desktop/package.json
  src/node/desktop/scripts/docker-run-unit-tests.sh
  src/node/desktop/src/main/utils.ts
Labels: electron

#10818 Run electron unit tests as part of the Windows build
  Jenkinsfile
  src/node/desktop/scripts/run-unit-tests.cmd
  src/node/desktop/test/unit/core/file-path.test.ts
  src/node/desktop/test/unit/main/desktop-browser-window.test.ts
  src/node/desktop/test/unit/main/gwt-window.test.ts
  src/node/desktop/test/unit/main/minimal-window.test.ts
  src/node/desktop/test/unit/main/satellite-window.test.ts
  src/node/desktop/test/unit/main/secondary-window.test.ts
  src/node/desktop/test/unit/main/window-tracker.test.ts
  src/node/desktop/test/unit/unit-utils.ts
Labels: automation

#10827 Build Windows Desktop with MSVC 2019 toolchain
  INSTALL
  Jenkinsfile
  dependencies/windows/Install-RStudio-Prereqs.ps1
  dependencies/windows/install-boost.cmd
  dependencies/windows/install-boost/install-boost.R
  dependencies/windows/install-dependencies.cmd
  dependencies/windows/install-openssl/install-openssl.R
  dependencies/windows/install-soci/install-soci.R
  dependencies/windows/install-yaml-cpp/install-yaml-cpp.R
  docker/jenkins/Dockerfile.windows
  docker/win-docker-build-image.cmd
  package/win32/codesign.bat
  package/win32/make-install-win32.bat
  package/win32/make-package.bat
  src/cpp/CMakeLists.txt
  src/cpp/tools/windows-dev.cmd
Labels: developer

#10851 use new icon for Electron desktop on Mac
  src/node/desktop/resources/icons/RStudio.icns
Labels: electron

#10852 Move where events are added on chunks to maintain scrolling fix on pages
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputFrame.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
Labels: bug, r markdown

#10853 Don't localize "untitled" for new doc filenames
  src/gwt/src/org/rstudio/studio/client/quarto/QuartoConstants.java
  src/gwt/src/org/rstudio/studio/client/quarto/QuartoConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/quarto/QuartoConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/quarto/ui/NewQuartoDocumentDialog.java
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.ui.xml
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooserRmdTemplateChooserUiBinderImplGenMessages_en.properties
  src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooserRmdTemplateChooserUiBinderImplGenMessages_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.java
Labels: locale

#10715 Add warnings for missing cookie
  src/cpp/server/auth/ServerAuthHandler.cpp
Labels: authentication, support

#10875 We don't use the electron-forge makers so remove them from package.json
  src/node/desktop/forge.config.js
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
Labels: builds, electron

#10882 Fix Electron --version switch
  src/node/desktop/NOTICE.electron
  src/node/desktop/package-lock.json
  src/node/desktop/package.json
  src/node/desktop/src/main/args-manager.ts
Labels: electron
