Repository rstudio/rstudio, pull requests merged in 2022-01, with the labels that each got.

#10222 feat(i18n): i18-nify RSConnect UIBinder files
  src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.ui.xml
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/AppNameTextbox.ui.xml
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/AppNameTextboxAppNameTextboxUiBinderImplGenMessages_en.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/AppNameTextboxAppNameTextboxUiBinderImplGenMessages_fr.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishRPubs.ui.xml
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishRPubsPublishRPubsUiBinderImplGenMessages_en.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishRPubsPublishRPubsUiBinderImplGenMessages_fr.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectAuthWait.ui.xml
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectAuthWaitRSConnectAuthWaitUiBinderImplGenMessages_en.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectAuthWaitRSConnectAuthWaitUiBinderImplGenMessages_fr.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectCloudAccount.ui.xml
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectCloudAccountRSConnectCloudAccountUiBinderImplGenMessages_en.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectCloudAccountRSConnectCloudAccountUiBinderImplGenMessages_fr.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.ui.xml
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeployRSConnectDeployUiBinderImplGenMessages_en.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeployRSConnectDeployUiBinderImplGenMessages_fr.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectLocalAccount.ui.xml
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectLocalAccountRSConnectLocalAccountUiBinderImplGenMessages_en.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectLocalAccountRSConnectLocalAccountUiBinderImplGenMessages_fr.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectNewAccount.ui.xml
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectNewAccountRSConnectNewAccountUiBinderImplGenMessages_en.properties
  src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectNewAccountRSConnectNewAccountUiBinderImplGenMessages_fr.properties
Labels: locale

#10249 Feature/i18n user prefs and state
  src/cpp/session/include/session/prefs/UserPrefValues.hpp
  src/cpp/session/prefs/UserPrefValues.cpp
  src/cpp/session/resources/schema/user-prefs-schema.json
  src/gwt/src/org/rstudio/core/client/widget/SelectWidget.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/Prefs.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessorConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessorConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalShellInfo.java
  src/gwt/tools/generate-prefs.R
  src/gwt/tools/prefs/UserPrefsAccessor.java
  src/gwt/tools/prefs/UserPrefsAccessorConstants.java
  src/gwt/tools/prefs/UserPrefsAccessorConstants_en.properties
  src/gwt/tools/prefs/UserStateAccessor.java
  src/gwt/tools/prefs/UserStateAccessorConstants.java
  src/gwt/tools/prefs/UserStateAccessorConstants_en.properties
Labels: locale

#10333 install panmirror node deps even if yarn already installed
  dependencies/common/install-yarn
Labels: developer

#10283 place conda utilities on PATH for windows
  NEWS.md
  src/cpp/session/modules/SessionTerminalShell.cpp
  src/cpp/session/resources/terminal/hooks
Labels: python

#10331 Inspection of incorrect localization
  src/gwt/src/org/rstudio/core/client/CoreClientConstants.java
  src/gwt/src/org/rstudio/core/client/CoreClient_en.properties
  src/gwt/src/org/rstudio/core/client/CoreClient_fr.properties
  src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants.java
  src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/application/ui/RequestLogDetail.java
  src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorConstants.java
  src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/projects/StudioClientProjectConstants.java
  src/gwt/src/org/rstudio/studio/client/projects/StudioClientProjectConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/projects/StudioClientProjectConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewPackagePage.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewQuartoProjectPage.java
  src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectSourceControlPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/ClientWorkbenchConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/output/OutputConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants_fr.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants.java
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants_en.properties
  src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/EditorsTextConstants_fr.properties
Labels: locale

#10346 Only run notarization logic on osx
  src/node/desktop/forge.config.js
Labels: electron

#10343 support C++ diagnostics etc with rtools42
  src/cpp/core/include/core/libclang/LibClang.hpp
  src/cpp/core/include/core/r_util/RToolsInfo.hpp
  src/cpp/core/r_util/RToolsInfo.cpp
  src/cpp/session/SessionModuleContext.cpp
  src/cpp/session/modules/SessionClang.R
  src/cpp/session/modules/build/SessionBuildEnvironment.cpp
  src/cpp/session/modules/clang/RCompilationDatabase.cpp
  src/cpp/session/modules/clang/RCompilationDatabase.hpp
  src/cpp/session/modules/clang/SessionClang.cpp
  src/cpp/session/modules/clang/SessionClang.hpp
Labels: c++

#10358 feat(i18n): update gwt.xml files
  src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
  src/gwt/src/org/rstudio/studio/RStudioDesktopSuperDevMode.gwt.xml
  src/gwt/src/org/rstudio/studio/RStudioSuperDevMode.gwt.xml
Labels: locale

#10477 Log to file for Electron desktop
  src/node/desktop/NOTICE.electron
  src/node/desktop/package.json
  src/node/desktop/src/core/core-state.ts
  src/node/desktop/src/core/logger.ts
  src/node/desktop/src/core/winston-logger.ts
  src/node/desktop/src/main/desktop-options.ts
  src/node/desktop/src/main/main.ts
  src/node/desktop/test/unit/core/console-logger.test.ts
  src/node/desktop/test/unit/core/file-path.test.ts
  src/node/desktop/test/unit/core/logger.test.ts
  src/node/desktop/yarn.lock
Labels: electron

#10479 use logging instead of console.log for Electron
  src/node/desktop/src/core/logger.ts
  src/node/desktop/src/core/winston-logger.ts
  src/node/desktop/src/main/application.ts
  src/node/desktop/src/main/desktop-browser-window.ts
  src/node/desktop/src/main/desktop-options.ts
Labels: electron

#10480 find M1 R installed by homebrew on Mac
  src/node/desktop/src/main/detect-r.ts
Labels: electron
